### ISSUE TITLE
Example of OR clause for select query

### ISSUE THREAD

**Issue by neocortical** [Masterminds/squirrel#102]
I am sure I will figure this out, but I have spent a fair amount of time trying to figure out how to generate a simple OR clause in a SELECT query. It would be great to have an example in the Godoc.

For example, how would one use Squirrel to generate the following: 
`SELECT * FROM users WHERE name = 'Alice' OR name = 'Bob';`

Thanks!

**Comment by lann** [comment]
I did a poor job of documenting this. Here is an example: https://github.com/Masterminds/squirrel/blob/v1/select_test.go#L28

I'll keep this open as a bug to improve the documentation.

**Comment by neocortical** [comment]
Thanks!

If I have a spare moment, I'll try to submit a PR of Godoc comments for `Or` and `And`.
