### ISSUE TITLE
Multiple tuple where clause

### ISSUE THREAD

**Issue by blockloop** [Masterminds/squirrel#104]
I'm trying to recreate this query with squirrel:

```
SELECT id, name
FROM users
WHERE ((name, age)) IN (('Alex', 10), ('Douglas', 40))
```

The closest I can come up with is this and it's wrong:

```
query := sq.Select("id, name").
	From("users").
	Where(sq.Eq{
		"((id, name))": []string{"('Alex', 10)", "('Douglas', 40)"},
	})
```

**Comment by lann** [comment]
Squirrel does not support tuples. You could rewrite the query with Or and Eq:
```go
sq.Or{sq.Eq{"name": "Alex", "age": 10}, sq.Eq{"name": "Douglas", "age": 40}}
```
If you have a fixed number of tuples in your IN clause, you could also write it with Expr:
```go
Expr("((name, age)) IN ((?, ?), (?, ?))", "Alex", 10, "Douglas", 40)
```
(examples untested)

**Comment by blockloop** [comment]
Closing because @lann's comment is sufficient to solve my issue

`sq.Or{sq.Eq{"name": "Alex", "age": 10}, sq.Eq{"name": "Douglas", "age": 40}}`

**Comment by MistaTwista** [comment]
If you need dynamic list of conditions sq.Or{} is an array. May be it will save your time :)
```golang
some := sq.Or{}
for _, data := range dataList {
  some = append(some, sq.Eq{"key1": data.Value1, "key2": data.Value2})
}
squirrel.Select(*).From("table").Where(some)
// SELECT * FROM table WHERE (key1 = $1 AND key2 = $2 OR key1 = $3 AND key2 = $4)
```

**Comment by vkhoroshavin** [comment]
> If you need dynamic list of conditions sq.Or{} is an array. May be it will save your time :)
> 
> ```go
> some := sq.Or{}
> for _, data := range dataList {
>   some = append(some, sq.Eq{"key1": data.Value1, "key2": data.Value2})
> }
> squirrel.Select(*).From("table").Where(some)
> // SELECT * FROM table WHERE (key1 = $1 AND key2 = $2 OR key1 = $3 AND key2 = $4)
> ```

it's not the same because "AND" has bigger priority then "OR"
