### ISSUE TITLE
Struggling to pass a dynamically-sized list into the DeleteBuilder

### ISSUE THREAD

**Issue by TannerMoore** [Masterminds/squirrel#105]
I am trying to setup explicit-transaction batching deletes in my program. The batch size is defined by the user. I want to take a list of variable size and run a delete query against my sql db.

The readme has an example of a statically-sized list being used in the query builder:

```
stooges := users.Where(sq.Eq{"username": []string{"moe", "larry", "curly", "shemp"}})
three_stooges := stooges.Limit(3)
rows, err := three_stooges.RunWith(db).Query()
```

I am trying to use the 

```
stooges := users.Where(sq.Eq{"username": []string{"moe", "larry", "curly", "shemp"}})
```
part, but still use the normal Exec call.

Here is what I have currently (I am going to change my static list to a dynamic list once I get it working):

```
func (p *Purger) purge(ctx context.Context, ids [][]int64) error {

	idMap := sq.Eq{"FileEvidenceID": []string{"238", "239", "240"}}

	deleteBuilder := sqlb.Delete("[CQDB].[dbo].[Evidence]").
			Where(idMap)

	query, params, err := deleteBuilder.ToSql()
	if err != nil {
		return err
	}

	tx, err := p.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.Exec(query, params)
	if err != nil {
		return err
	}
	tx.Commit()
	return nil
}
```

But I am getting this error:

```
sql: expected 3 arguments, got 1
```

I dug in a bit with the gogland debugger and it seems like the arguments parser gets the `3` from the contents of the map, but at the end compares the number of map entries to the total number of maps `1`

Is the argument parser bugged? Am I doing something wrong?

**Comment by lann** [comment]
The `tx.Exec` method is variadic (the `...` in the [signature](https://golang.org/pkg/database/sql/#Tx.Exec)), which means it is usually called like `tx.Exec("? ? ?", arg1, arg2, arg3)`. In order to "expand" the list of arguments in `params` you need to use `tx.Exec(query, params...)`.

**Comment by TannerMoore** [comment]
Ah yes, I didn't think about the expansion behind the scenes. Thank you
