### ISSUE TITLE
[PROPOSE] Add optional support of 'jmoiron/sqlx' library

### ISSUE THREAD

**Issue by x1unix** [Masterminds/squirrel#107]
Please add optional support for [jmoiron/sqlx](https://github.com/jmoiron/sqlx/) library.
Thank you! :)

**Comment by 3timeslazy** [comment]
Did you mean smth like this?
```golang
db := sqlx.MustConnect(driver, dsn)
sq.Select("id").Where(sq.Eq{"id": 0}).RunWith(db)
```

**Comment by x1unix** [comment]
@3timeslazy I meant to be able to use `*sqlx.DB` as argument for `RunWith()` method

**Comment by 3timeslazy** [comment]
@x1unix why not use `sqlx.DB.DB`?

**Comment by nick4fake** [comment]
@3timeslazy because of automatic mapping
