### ISSUE TITLE
Constructed insert is incorrect when calling Values multiple times

### ISSUE THREAD

**Issue by tasdomas** [Masterminds/squirrel#108]
With squirrel.v1, if I run this code:
```
        ins := squirrel.Insert("a")
        ins = ins.Columns("b", "c").Values("b1", "c1").Columns("d").Values("d1")
        q, v, err := ins.ToSql()
        fmt.Printf("%v\n", q)
        fmt.Printf("%+v\n", v)
        fmt.Printf("%v\n", err)
```

The insert statement is generated incorrectly: `INSERT INTO a (b,c,d) VALUES (?,?),(?)`

**Comment by lann** [comment]
["Values adds a single row's values to the query."](https://godoc.org/github.com/Masterminds/squirrel#InsertBuilder.Values)

So Columns and Values are a little inconsistent in that multiple calls to Columns will extend the column list while multiple calls to Values adds rows. This is annoying but probably can't be fixed without breaking backwards compat.

**Comment by cmars** [comment]
If multiple calls to `Values` with a mismatched number of arguments results in invalid SQL, I'd prefer to see that cause an error (perhaps on `.ToSql`?) rather than undefined behavior.

**Comment by lann** [comment]
For the most part I have not implemented errors where the database parser will immediately error anyway. I have reserved errors for cases where squirrel could produce syntactically-valid but misleading SQL.
