### ISSUE TITLE
add unquoted placeholder option to Expr 

### ISSUE THREAD

**Issue by dnldd** [Masterminds/squirrel#109]
Squirrel quotes all arguments passed to `Expr`, this works well for simple KV but generates invalid queries for sql functions like Postgres' jsonb functions. A query like:

 `sq.DebugSqlizer(sq.Update(table).Set(dataset, sq.Expr("jsonb_insert(?, '{0}'::text[],to_jsonb(?::text),true)", dataset, newEntry)).Where(sq.Eq{whereColumn: *whereValues}))`

on a table (`invoice`) with a jsonb column (`receipts`) resolves to:
 
`UPDATE invoice SET receipts = jsonb_insert('receipts', '{0}'::text[],to_jsonb('xxxxx'::text),true) WHERE uuid IN ('xxxxx')`

The quoted `receipts` argument passed to `jsonb_insert` makes the query invalid:

`pq: could not determine data type of parameter $2`

I think`Expr` should have an unquoted placeholder.

**Comment by lann** [comment]
The DebugSqlizer function does not necessarily match what the database is seeing (see its [doc comment](https://godoc.org/github.com/Masterminds/squirrel#DebugSqlizer)). I believe this is the underlying pq database driver telling you it doesn't know how to resolve the type of `newEntry`.

**Comment by dnldd** [comment]
if `Set(column string, value interface{})` always quotes the value provided then how do you pass a function as a value?

**Comment by lann** [comment]
Squirrel does not - in general - do any value quoting. It passes the values on to the db engine (pq in this case). If the engine doesn't know how to deal with a value type you will get an error. To see exactly what is being passed to the engine you can do something like (untested):

```go
sql, args, err := sq.Update(table) // Finish expression here
fmt.Printf("sql = %q\nargs = %#v\nerr = %v\n", sql, args, err)
```

**Comment by dnldd** [comment]
alright thanks, will have another go in a couple of hours.

**Comment by arpanetus** [comment]
@dnldd hey have you done smth on it already?
