### ISSUE TITLE
Placeholders interpolation

### ISSUE THREAD

**Issue by JordanP** [Masterminds/squirrel#110]
Hi,
I'd like to cache SQL query result. To do that, I need a cache key. Currently `ToSQL()` returns a `string, []interface{}`. The second part is obviously not hashable, so you get the usual `hash of unhashable type` error if you want to use that as a cache key. Any idea on how to get like a simple string that would "represent"/"identify" uniquely a query and its parameters ?

**Comment by lann** [comment]
It's going to depend on your use case, but you could *probably* get away with serializing the `[]interface{}` with `encoding/gob` and appending that to the sql string from `ToSql()`.

Going beyond your actual question: in my experience this kind of generic caching doesn't work very well. You often end up with a "long tail" of unique queries filling up your cache. Better to cache at a higher level, i.e. wrap your query in a function and cache based on the function arguments instead. Anyway, you know your problem better than I do, so take that with a grain of salt.

**Comment by JordanP** [comment]
Thank you ! It helped me a lot. I'll explore the 2 options :)

(I consider this "issue" solved, feel free to close it)
