### ISSUE TITLE
Composite Primary Keys

### ISSUE THREAD

**Issue by FourSigma** [Masterminds/squirrel#113]
How do I execute the following query with composite keys and an array of tuple values? 

SELECT * FROM student_course WHERE (student_id, course_id) IN ( (1,2), (42,23) );

**Comment by lann** [comment]
Previously answered in #104.

**Comment by FourSigma** [comment]
@lann Would you be interested in merging a pull request that supported tuples for IN clauses?

**Comment by lann** [comment]
Sure! If you are willing to do so please propose a syntax for it before doing too much work. I want to be careful about maintaining backward compatibility.
