### ISSUE TITLE
SelectBuilder.Where() broken

### ISSUE THREAD

**Issue by hahanein** [Masterminds/squirrel#114]
Version: a6b9300

Where statements aren't being transformed into "WHERE IN (?, ...)" statements if the value of a `squirrel.Eq` key is of type `[]uint8`.

### Correct:

```go
package main

import (
        "fmt"

        "github.com/Masterminds/squirrel"
)

func main() {
        query, args, err := squirrel.Select("*").Where(squirrel.Eq{"test": []uint32{1, 2, 3}}).ToSql()
        if err != nil {
                panic(err)
        }

        fmt.Println(query) // SELECT * WHERE test IN (?,?,?)
        fmt.Println(args) // [1 2 3]
}
```

### Bug:

```go
package main

import (
        "fmt"

        "github.com/Masterminds/squirrel"
)

func main() {
        query, args, err := squirrel.Select("*").Where(squirrel.Eq{"test": []uint8{1, 2, 3}}).ToSql()
        if err != nil {
                panic(err)
        }

        fmt.Println(query) // SELECT * WHERE test = ?
        fmt.Println(args) // [[1 2 3]]
}
```

**Comment by lann** [comment]
Squirrel doesn't touch values when [`driver.IsValue(value)`](https://golang.org/pkg/database/sql/driver/#IsValue) is true. It looks like [`byte` is really just an alias for `uint8`](https://golang.org/pkg/builtin/#byte), and [`driver.IsValue([]byte{})` is true](https://golang.org/src/database/sql/driver/types.go?s=5107:5113#L175).

I don't think this can be fixed backward-compatibly.

**Comment by hahanein** [comment]
Thank you! Maybe you should warn about this pitfall in the README and the docs.

**Comment by lann** [comment]
Good idea. Added an FAQ section with this.

**Comment by sundowndev** [comment]
Wouldn't it be possible to introduce a `squirrel.In{}` type ?
