### ISSUE TITLE
Support appending values to InsertBuilder 

### ISSUE THREAD

**Issue by devarsh** [Masterminds/squirrel#115]
Hi,

I've been trying to create a middleware from where all the inserts would be processing, and would be taking insertBuilder as input and adding common columns i.e insert_At [time] , update_At[time], to each insert processed, but calling _InsertBuilder.Values_ again appends another row, so is there a way to call _InsertBuilder.Values_ multiple time and add values to the existing result set

```go

insertQuery := sq.Insert("country_mst").
		Columns("id", "name", "short_name").
		Values(insertId, countryName, shortName)

....Middleware...
		insertQuery = insertQuery.
			Columns(CreatedAt, UpdatedAt).
			Values(time.Now(), time.Now()).
			PlaceholderFormat(sq.Dollar)
```

**Current Output**
```go
INSERT INTO country_mst (id,name,short_name,created_at,modified_at) VALUES ($1,$2,$3),($4,$5)
``` 

($1,$2,$3) 1st Row
($4,$5) 2nd Row

**Desired Output**
```go 
INSERT INTO country_mst (id,name,short_name,created_at,modified_at) VALUES ($1,$2,$3,$4,$5)
```

($1,$2,$3,$4,$5) In the same row and not add another row for each call to _InsertBuilder.Values_

**Comment by devarsh** [comment]
Apologies, the same could be achieved with triggers.

**Comment by fterrag** [comment]
@devarsh +1 on this suggestion.

For now, you can use SetMap:

```
SetMap set columns and values for insert builder from a map of column name and value note that it will reset all previous columns and values was set if any
```

**Comment by lann** [comment]
I think this could be done with a new method `AppendColumn(name string, defaultValue interface{})` where `defaultValue` is appended to each row that has already been added to the insert.

**Comment by eyJhb** [comment]
If anyone finds this like I did, then I ended up doing this.

```go
// stmtInsert = AppendToValues(stmtInsert, "test", "test2")
func AppendToValues(b sq.InsertBuilder, values ...interface{}) sq.InsertBuilder {
	// ignore the boolean, as we will always have `Values`
	oldValues, _ := builder.Get(b, "Values")

	var newValues [][]interface{}
	for _, val := range oldValues.([][]interface{}) {
		newValues = append(newValues, append(val, values...))
	}

	return builder.Set(b, "Values", newValues).(sq.InsertBuilder)
}
```

There might be a better/prettier solution, but this works OK.
Anyone that can come up with a more sleak way, please show it!

Also, I really think that squirrel could benefit from having this standard in the library @lann , however this solution is OK for me for now. Thanks for the library!
