### ISSUE TITLE
Debugger bug

### ISSUE THREAD

**Issue by sluchznak** [Masterminds/squirrel#116]
Hello guys! I think this is a bug.

```go
q := sq.Select("id").
	From("users").
	Where(sq.Eq{"id": 1}).
	RunWith(r.DB).
	PlaceholderFormat(sq.Dollar)
log.WithField("sql", sq.DebugSqlizer(q)).Warn("Debug select query")
```

```log
WARN[2018-02-03T12:04:32+06:00] Debug select query                            sql="[DebugSqlizer error: not enough placeholders in \"SELECT id FROM users WHERE id = $1\" for 1 args]"
```

go version: 1.9.3
squirrel revision: f3d8be4
db: postgresql

**Comment by lann** [comment]
Yes, this is a bug. A workaround:

```go
sq.DebugSqlizer(q.PlaceholderFormat(sq.Question))
```

I probably won't get to fixing this very soon, but I think something like this would do it (untested and somewhat hacky):

```go
func DebugSqlizer(s Sqlizer) string {
  if b, ok := s.(builder.Builder); ok {
    b = b.Set("PlaceholderFormat", sq.Question)
    s = b.(Sqlizer)
  }
...
}
```

**Comment by thmsweaver** [comment]
@sluchznak is this now resolved for you?

**Comment by sluchznak** [comment]
> @sluchznak is this now resolved for you?

I don't know

**Comment by chrisbbe** [comment]
No, its not.

**Comment by chrisbbe** [comment]
@sluchznak @thmsweaver Seems a fix for this issue is merged, but not released. The last release is v1.1.0 in Januar 2018.

@lann When will next release be?
