### ISSUE TITLE
Placeholder does not get recognised within JSON function

### ISSUE THREAD

**Issue by Jleagle** [Masterminds/squirrel#117]
I have a where condition in my select query:
> builder.Where("JSON_CONTAINS(platforms, '[\\"?\\"]')", "windows")

But i get the error:

> sql: statement expects 0 inputs; got 1

I believe it is not seeing the `?`

**Comment by lann** [comment]
That error is coming from your db driver, not squirrel.

**Comment by lann** [comment]
Are you sure you don't just want ```.Where("JSON_CONTAINS(platforms, ?)", "windows")```? I'm not familiar with Mysql's JSON support.

**Comment by Jleagle** [comment]
JSON requires double quotes around strings, so

> select * from apps where JSON_CONTAINS(platforms, '["linux"]');

is valid, while

> select * from apps where JSON_CONTAINS(platforms, '[linux]');

is not valid. I took your idea of adding quotes to the value, like so:

Where("JSON_CONTAINS(platforms, '[?]')", "\\"" + query.Get("platforms") + "\\"")

but i get the same error.

**Comment by lann** [comment]
The ? placeholder cannot appear in a string literal (single quotes) and still act like a placeholder.

If your example above is correct:

```sql
select * from apps where JSON_CONTAINS(platforms, '["linux"]');
```

then you would need to write it as:

```go
builder.Where("JSON_CONTAINS(platforms, ?)", "[\"" + query.Get("platforms") + "\"]")
```

**Comment by Jleagle** [comment]
Thank you
