### ISSUE TITLE
Outer joins?

### ISSUE THREAD

**Issue by ns-cweber** [Masterminds/squirrel#118]
I couldn't find anything in the documentation.

**Comment by neocortical** [comment]
+1 to this. Generally, some quick examples of how to create JOINs with and without parameters would be really awesome. It is not obvious to me from the GoDoc.

**Comment by inuishan** [comment]
+1. Outer joins not supported? Checked the source and it doesn't seem like there is support for it.

**Comment by lann** [comment]
`LeftJoin` and `RightJoin` cover the common outer joins. It isn't well documented, but the `JoinClause` method allows any join syntax:

https://github.com/Masterminds/squirrel/blob/v1/select_test.go#L20

Parameters are supported as with other squirrel methods:

https://github.com/Masterminds/squirrel/blob/v1/select_test.go#L134
