### ISSUE TITLE
SQL query cannot take more than 32768 parameters.

### ISSUE THREAD

**Issue by ghost** [Masterminds/squirrel#120]
When I am writing a bulk insert statement, where i have eg 10 columns and 5000 rows, the insert query fails. This is the error I get pq: there is no parameter $-32768.

db: postgresql

**Comment by lann** [comment]
Squirrel uses an int32 for that generation. I think this is most likely a bug in pq.

To verify, try:

```go
sql, _, _ := yourQuery.ToSql()
```

And print `sql` to see what is generated there.

**Comment by sohilgogri** [comment]
It does print out the query with the ?'s as parameters. Maybe it is a bug in pq. 
Thanks

**Comment by rusq** [comment]
@sohilgogri Which version of Postgres are you using?
