### ISSUE TITLE
Add .MustSql() to avoid error checking when building queries

### ISSUE THREAD

**Issue by benhoyt** [Masterminds/squirrel#126]
The `.ToSql()` function returns `query, args, err`, but query building errors are almost always programming bugs (and not user input errors) so it makes more sense to panic on error. For example, there errors are things like invalid types, not specifying a table name, etc. It's easy to ignore the error by doing `query, args, _ := query.ToSql()` but ignoring the error is not good either -- it'll mask programming bugs.

So my suggestion is to add a `.MustSql()` method that returns just `query, args`. It would basically be a call to `ToSql()` and then panic if the error is non-nil. We've actually added our own function which does just this, but it's not part of the fluent interface, so not so nice.

**Comment by lann** [comment]
Thanks!
