### ISSUE TITLE
Programmatic build of OR clauses

### ISSUE THREAD

**Issue by panta** [Masterminds/squirrel#127]
I need to programmatically build some OR clauses like in the following statement:

```
SELECT ... FROM mytable WHERE ... AND ((kind = 'ABC') OR (kind = 'DEF') OR (kind = 'XYZ')) AND ...
```

where the code building the clause is like:

```
	var sb sq.SelectBuilder
	...

	// ugly hack
	q_kind := sq.Or{sq.Expr("false"), sq.Expr("false")}

	for _, v := range kindValues {
		switch v {
		case "1":
			q_kind = sq.Or{q_kind, sq.Eq{"kind": "ABC"}}
		case "2":
			q_kind = sq.Or{q_kind, sq.Eq{"kind": "DEF"}}
		...
		case "42":
			q_kind = sq.Or{q_kind, sq.Eq{"kind": "XYZ"}}
		}
	}
	sb = sb.Where(q_kind)
```

I've had to resort to the `sq.Or{sq.Expr("false"), sq.Expr("false")}` ugly hack to have an initial condition to append the actual Or clauses later on.
The generated SQL then contains the `(false OR false) OR ...` which I'd like to avoid...

(Note that the above code and values are for illustrative purposes, the actual query is more meaningful :-)

Is there a cleaner way to build such a condition?

**Comment by lann** [comment]
Eq supports `IN` expressions.
```go
sq.Eq{"kind": []string{"ABC", "DEF"}}
```
generates something like ```kind IN ('ABC', 'DEF')```

An empty slice evaluates to false.
