### ISSUE TITLE
Empty sq.Eq{} in .Where() cause causes  pq: syntax error at end of input

### ISSUE THREAD

**Issue by scottschulthess** [Masterminds/squirrel#131]
Hello, thanks for this project! 

I'm conditionally building a query like so 

``` 
fields := sq.Eq{}
if len(someField) > 0 {
fields["column"] = someField
}
sql, args, _ := psql.Select("fields").From("table").Where(fields).ToSql()
```
But this generates the following error
```
pq: syntax error at end of input
```

Assuming this makes sense I will look into opening a PR for this issue

**Comment by lann** [comment]
I assume you are getting that error when you execute the code on the database; what is the generated sql?

**Comment by scottschulthess** [comment]
Also I do happen to execute this using sqlx

``` 
rows, err = d.selectRows(sql, args...)
``` 
not sure if that is a factor

**Comment by lann** [comment]
Ah, I see. Yes, I guess an empty Eq{} should eval to literal true,

**Comment by scottschulthess** [comment]
awesome @lann !
