### ISSUE TITLE
Jsonb

### ISSUE THREAD

**Issue by ldelossa** [Masterminds/squirrel#134]
Hey guys,

Can I use jsonb syntax for attribute selection like:

"SELECT w FROM workouts WHERE (w->>'id') = ($1);"

**Comment by lann** [comment]
I would expect this to work (untested):

```go
.Where("(w->>'id') = (?)", id)
```

**Comment by ldelossa** [comment]
@lann is there a way to combine this with an IN operator ?

**Comment by lann** [comment]
Untested, but I would expect this to work:
```go
.Where(sq.Eq{"(w->>'id')": []interface{1,2,3}})
```
