### ISSUE TITLE
SQL Consistency in `sq.Eq` 

### ISSUE THREAD

**Issue by Carlangueitor** [Masterminds/squirrel#135]
Should the same builder and params generate ALWAYS the same SQL? For example, the next code:

```
        users := sq.Select("*").From("users").Where(sq.Eq{
                "status": "active",
                "site":   "main",
        })
```
Sometimes the generated SQL is  `SELECT * FROM users WHERE status = ? AND site = ?` and sometimes generates `SELECT * FROM users WHERE site = ? AND status = ?` (different order of parameters). In the practice it doesn't affect because the query arguments are in the same order as params, but, for example, in my case, I was mocking my `*sql.DB` with  [go-sqlmock](https://github.com/DATA-DOG/go-sqlmock), and I needed to point out the arguments in the same order as passed.

A workaround to this is to use only one parameter per `Eq`, e.g:

```
        users := sq.Select("*").From("users").
                Where(sq.Eq{"status": "active"}).
                Where(sq.Eq{"site": "main"})
``` 

It looks like as `sq.Eq` is a map and maps iteration order is randomized by the runtime, it can be fixed by putting some order [before iterating the map](https://github.com/Masterminds/squirrel/blob/b127ed9be03443fe3c0877e391130e3dd3f3107a/expr.go#L102), it makes sense for you? Can this fix be a problem with the performance?

**Comment by lann** [comment]
I thinking sorting would be fine. I'm generally not concerned with small performance issues at SQL generation time since you are generally about to send the SQL to the (presumably much slower) DB engine.

**Comment by Carlangueitor** [comment]
Ok, I'm going to work on a PR for that :+1:

**Comment by jtamary** [comment]
I had the same issue. Added a pull request. Let me know if some changes need to be done :)
