### ISSUE TITLE
Increment column

### ISSUE THREAD

**Issue by matteosuppo** [Masterminds/squirrel#136]
Suppose I wanted to execute this query on postgres:

```
UPDATE my_table SET amount=amount+5 WHERE id=0
```

Is there a way to build it with squirrel?

**Comment by lann** [comment]
It looks like that is not currently possible. I think a `SetExpr` method would need to be added to UpdateBuilder to support that syntax.

**Comment by matteosuppo** [comment]
I found a way, maybe:

```go
_, err = db.Update("my_table").
	Set("amount", squirrel.Expr("amount+5")).
	Where(sq.Eq{
		"id": user,
	}).Exec()
```

**Comment by lann** [comment]
Ah yes, that should work. I haven't looked at that code in too long...

**Comment by matteosuppo** [comment]
Thank you very much, it was the `SetExpr` that made me look at what an Expr was
