### ISSUE TITLE
PlaceHolderFormat for oracle

### ISSUE THREAD

**Issue by mahranben** [Masterminds/squirrel#138]
Hi,
I'm new to Go programming, so i've been using squirrel for db querying which is being very useful. 
But I can't figure out a way to change the PlaceholderFormat querying against oracle (":" instead of "$" for postgres)
Is it possible to do so ?

**Comment by lann** [comment]
You would need a new implementation of the PlaceholderFormat interface: https://github.com/Masterminds/squirrel/blob/v1/placeholder.go

If you come up with a general solution I'd be happy to accept a PR.

**Comment by mahranben** [comment]
Thanks for reply. I'll take a look into it
