### ISSUE TITLE
Support for MySQL's WITH clause

### ISSUE THREAD

**Issue by amogh09** [Masterminds/squirrel#149]
I couldn't find any documentation for MySQL's WITH clause. Does Squirrel support it? If not, it'd be great to have it as I think WITH clause is highly convenient. 

https://dev.mysql.com/doc/refman/8.0/en/with.html

**Comment by lann** [comment]
Squirrel does not generally support dialect-specific extensions, but it does have a generic Prefix method that can be used for things like this.

**Comment by amogh09** [comment]
Thank you for the clarification.
