### ISSUE TITLE
Deletebuilder and queryrow

### ISSUE THREAD

**Issue by matteosuppo** [Masterminds/squirrel#158]
When I'm deleting a row, I have to select some related resources (such as a filesystem path) to clean up properly.

With squirrel I'm using a Select and a Delete, but with a single query I could do

```
DELETE FROM table WHERE id=55 returning path;
```

I can't make it work with squirrel because DeleteBuilder doesn't have QueryRow. Any ideas on how I could make it work?

**Comment by lann** [comment]
As a workaround you can manually pass the output of ToSql to your DB. I would accept a patch adding Query/QueryRow to the other statement builders but I probably won't get to it myself soon.

**Comment by sivagollapalli** [comment]
@matteosuppo I couldn't able to understand the issue? Could you provide a failing test case so I would like to give a shot?

**Comment by matteosuppo** [comment]
The issue is that 

```
	rows, err := squirrel.Delete("table").
		Where("id=55").
		Suffix("RETURNING path").Query()
```

doesn't compile, because DeleteBuilder doesn't have `.Query` or `.QueryRow`.

**Comment by sivagollapalli** [comment]
@lann Added `Query()` to delete builder. Could you please check?

**Comment by lann** [comment]
Merged. Thanks for the contribution.
