### ISSUE TITLE
Update gopkg

### ISSUE THREAD

**Issue by dominicbarnes** [Masterminds/squirrel#167]
It looks like https://gopkg.in/Masterminds/squirrel.v1 is pointing to the v1.0 tag, which is well over a year old. Would it be possible to get another tag published to update gopkg a little bit?

**Comment by dominicbarnes** [comment]
I'm switching to `master` for the short-term, but would definitely prefer gopkg for the long-term.

**Comment by lann** [comment]
Hmm...I didn't realize that it was pointing to the tag rather than the v1 branch. Note that the v1 branch is the default git branch (i.e. what you get by default if you clone).

**Comment by pzduniak** [comment]
It also messes up package managers, which resolve by tag rather by the branch.

**Comment by lann** [comment]
Tagged `v1.1`
