### ISSUE TITLE
Create tables/indexes

### ISSUE THREAD

**Issue by nanom1t** [Masterminds/squirrel#174]
Hi,

How to create/drop tables/indexes in database using squirrel? 

It is a part of SQL, but I don't see any methods for this purposes.

```
CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255) 
);
```

Thanks

**Comment by lann** [comment]
Squirrel does not support SQL DDL.

**Comment by nanom1t** [comment]
It would be a great feature for squirrel.

**Comment by PrakharSrivastav** [comment]
Would love the support for this feature. My use case involves generating tables on the fly for the ETL type of computations. Currently, I am generating SQL query by concatenating strings, which of course is extremely hacky. Support for creating / dropping tables will be amazing to have

**Comment by achandak123** [comment]
Any update on this one? What are folks using for this, if not squirrel?

**Comment by PrakharSrivastav** [comment]
@achandak123: I ended up creating something of my own for this purpose. You can check it [sql-query-builder](https://github.com/PrakharSrivastav/sql-query-builder). Currently, it only supports create table, but it is easy to extend.
