### ISSUE TITLE
Existing tags are not useable with Go modules

### ISSUE THREAD

**Issue by clarafu** [Masterminds/squirrel#176]
When running `go get github.com/Masterminds/squirrel@v1.1`, it fails with `no matching versions for query "v1.1"`. I'm assuming this is because the tag only has two version segments and Go's module system wants strict semver versions like v1.1.0.

Would you mind adding/updating the tags for this?

Thanks!

**Comment by lann** [comment]
v1.1.0 published

**Comment by igungor** [comment]
Still not usable with Go1.11.4, modules enabled.

```
Δ go get gopkg.in/Masterminds/squirrel.v1
go: finding gopkg.in/Masterminds/squirrel.v1 v1.1.0
go: gopkg.in/Masterminds/squirrel.v1@v1.1.0: go.mod has non-....v1 module path "github.com/Masterminds/squirrel" at revision v1.1.0
go: error loading module requirements

Δ go version
go version go1.11.4 darwin/amd64
```

**Comment by bobbytables** [comment]
Also seeing this:

```
go get gopkg.in/Masterminds/squirrel.v1
go: finding gopkg.in/Masterminds/squirrel.v1 v1.1.0
go: gopkg.in/Masterminds/squirrel.v1@v1.1.0: go.mod has non-....v1 module path "github.com/Masterminds/squirrel" at revision v1.1.0
go: error loading module requirements
```

Is it me?

**Comment by lann** [comment]
I have removed references to gopkg.in from the README. With go modules it isn't really useful and is probably causing your issue.
