### ISSUE TITLE
Insert DEFAULT value in postgres

### ISSUE THREAD

**Issue by cam-hashemi** [Masterminds/squirrel#184]
I am looking to generate a statement like this:

`INSERT INTO table_name (id,created_at,updated_at) VALUES (DEFAULT,DEFAULT,DEFAULT)`

using:

`sqrl.Insert("table_name").Columns("id","created_at","updated_at").Values("default","default","default").toSql()`

DEFAULT is a keyword in postgres that populates the values with the column defaults.

However, if I use placeholder substitution here, "DEFAULT" is converted to a literal string.

Is there any way to generate this DEFAULT keyword?

Or is there a way I can work around it in a nice way?

**Comment by bertrand-caron** [comment]
I believe using `sqrl.Expr("DEFAULT")` instead of `"DEFAULT"` might work. I agree that this feature might be under-documented though.
