### ISSUE TITLE
when use sq.Eq{} in where, Tosql get different sql

### ISSUE THREAD

**Issue by yyjia** [Masterminds/squirrel#191]
for example:
query, args := sq.Delete(TableName).
		Where(sq.Eq{"position_id": positionID, "platform_id": platformID, "group_id": groupIDs}).
		ToSql()
can get different sql , the where  with different order like:
where position_id = ? and platform_id = ? and group_id = ?
where platform_id = ? and group_id = ? and position_id = ?
where group_id = ? and  position_id = ? and platform_id = ?

when we use sqlmock , may get  manay bug

**Comment by yyjia** [comment]
can make Tosql()   get the same sql ?

**Comment by lann** [comment]
This looks the same as #135. Are you using an old version?
