### ISSUE TITLE
add ScanMap() for reads analogue to SetMap() for writes

### ISSUE THREAD

**Issue by cben** [Masterminds/squirrel#193]
I'd love a ~~SelectBuilder~~ `ScanMap()` counterpart to `Scan()`, similar to InsertBuilder/UpdateBuilder `SetMap()` conterpart to `Values()`.

Something in the spirit of:
```go
From("tableA").
Join("tableB").
ScanMap(map[string]interface{} { 
	"tableA.colA": &fieldA, 
	"tableB.colB": &fieldB,
})
```

Wait actually it can't simply be on SelectBuilder, it'll have to be on rows iterator for multi-row scans.  Except SelectBuilder does want to see the map to get the list of columns :thinking:

What do you think?  If you see an interface that works, I'm happy to work on a PR.

----

I have 2 motivations:

1. With a lot of columns (we have a query with over 40), listing them separately in `Select("colA", ..., "colZ")....Scan(&fieldA, ..., &fieldZ)` quickly gets very error-prone.

2. I want to isolate a layer doing some custom mapping of written/read values, partially in Go partially in SQL, which intrudes in multiple places.
  I'm dealing with dynamic subsets of columns in `Update().SetMap()` anyway, and turns out a map is actually easy to pre-process in an isolated function.
  So if I could have read code also go through a map, I could similarly have an isolated function that replaces some columns pointers with an `sql.Scanner` implementation that transforms the value and writes back into the original pointer.
  (Yes, I know `sql.Valuer` and `sql.Scanner` are nice, but I don't want my business logic to deal with any custom types; after the transform layer I want to deal with native int, string etc...)

----

I see `sqlx` has `MapScan()` that *builds a map* of everything the query returned https://jmoiron.github.io/sqlx/#altScanning  
I'm more interested in passing a map, and also deriving Select() columns from it, if possible.

**Comment by lann** [comment]
This seems pretty specific to be included in this library. It seems like it would be pretty straightforward to implement your own function using [`Rows.Columns()`](https://golang.org/pkg/database/sql/#Rows.Columns) to match the map keys.

**Comment by cben** [comment]
Rows.Columns() is what sqlx MapScan() does, my understanding is it has problems with joined `tablea.foo` vs `tableb.foo` and computed expressions.

I'd rather match up to whatever expressions I feed to Select(), which is why I thought of giving a map in one call doing both Select and Scan.  But the iteration _is_ a problem...

I'm gonna build something in my code and come back if I find an interface suitable for squirrel, but yeah it likely belongs outside.
