### ISSUE TITLE
Update query with Join and set

### ISSUE THREAD

**Issue by achandak123** [Masterminds/squirrel#195]
How do i write a query like 
```
UPDATE Access access JOIN AssumedRole assumedRole ON access.IdentityURI = assumedRole.ID SET access.IdentityURI = assumedRole.IdentityURI, access.RoleURI = assumedRole.RoleURI WHERE assumedRole.ID IN ("foo") 
```

Issue is I need to call SET with a variable name like assumedRole.IdentityURI, but that variable is defined in the query.

I tried this, but this doesnt work

```
updateQuery := sq.Update(" Access access").Join("AssumedRole assumedRole ON access.IdentityURI = assumedRole.ID ").SET("access.IdentityURI", "assumedRole.IdentityURI").SET("access.RoleURI", "assumedRole.RoleURI").Where(sq.Eq{"assumedRole.ID": assumedRoleIDs})
```
This sets the IdentityURI in access table to just assumedRole.IdentityURI, instead of the value of assumedRole.IdentityURI.

**Comment by lann** [comment]
Something like this should work:
```
.Set("access.RoleURI", squirrel.Expr("assumedRole.RoleURI"))
```
The `Expr(...)` here tells squirrel to treat the string as literal SQL instead of a string parameter.

**Comment by allenhsu** [comment]
Hi @achandak123 @lann, I'm writing a similar SQL (UPDATE ... JOIN ON ... SET ... pattern), but I cannot find `Join` method in `UpdateBuilder`'s definition. How should I build such SQL with squirrel? Thanks for your help!
