### ISSUE TITLE
Subselect in update statement

### ISSUE THREAD

**Issue by arch1tect0r** [Masterminds/squirrel#196]
Hello!

I try to generate update query with subselect but it's not working.

Example: https://play.golang.org/p/bOzp2Kyq1yh

The result should be

```sql
update another_table set data_id = (select id from data_table where title = $1) another_pk = $2
```

**Comment by lann** [comment]
Yeah, there is a weakness in the interface design that requires this kind of feature to be added piecemeal. This one would require a new else/if branch here: https://github.com/Masterminds/squirrel/blob/master/update.go#L81

**Comment by arch1tect0r** [comment]
As I understand. This problem also exists in insert statement, am I right?

**Comment by lann** [comment]
Yes: https://github.com/Masterminds/squirrel/blob/master/insert.go#L116

**Comment by Shamus03** [comment]
For now you could use `sq.Expr` and wrap the inner select in parens: https://play.golang.org/p/-bE7gpsxKt_t

```go
package main

import (
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

func main() {
	modelSubQuery := sq.
		Select("id").
		From("data_table").
		Where("title = ?", "TEST")

	b := sq.
		Update("another_table").
		Set("data_id", SubQuery(modelSubQuery)).
		Where("another_pk = ?", "234").
		PlaceholderFormat(sq.Dollar)

	bsql, _, _ := b.ToSql()

	fmt.Println(bsql)
}

// package squirrel
func SubQuery(sb sq.SelectBuilder) sq.Sqlizer {
	sql, params, _ := sb.ToSql()
	return sq.Expr("("+sql+")", params)
}
```
