### ISSUE TITLE
How to compare two fields?

### ISSUE THREAD

**Issue by dongfengkuayue** [Masterminds/squirrel#198]
SQL like "field1<?" can be parsed as Lt{"field1":1}.
But how about "field1 < field2"? How to parse it  into squirrel language?

**Comment by dongfengkuayue** [comment]
> `.Where("field1 < field2")`
Can't it be built with API structs like 'LT/Gt' and generated automatically by `.ToSql()` method ?
IMO, the code style of writing code like `.Where("field1 < field2")` is not consistent with that of `Gt{"filed1":1}`.

**Comment by lann** [comment]
The comparison helpers like `Lt` are optimizing for the more common case of literal values. Something like `Lt{"field1", sq.Expr("field2")}` could be made to work (I don't think it does currently), but that doesn't seem significantly easier than `"field1 < field2"`.

**Comment by artlo** [comment]
It can be helpful for building Join with multiple conditions on few fields. Now I have to use strings.Join `(["t1.f1` = t2.f2", "t1.f2 =t2.f3"], " and ")`

**Comment by artlo** [comment]
@lann , Thank you! I've also found this solution after detail reading this thread.
