### ISSUE TITLE
A subselect in a join clause

### ISSUE THREAD

**Issue by lorencio1** [Masterminds/squirrel#199]
Is it possible to build a query which has a subselect in its join clause?

```
SELECT ...
FROM ...
JOIN (SELECT ...
      FROM ...
     ) AS ... ON ...
```

**Comment by prochac** [comment]
can you accept something like this??
https://play.golang.org/p/2Iotz1428n4

**Comment by lann** [comment]
The tests show a (somewhat awkward) way to do this with `JoinClause`: https://github.com/Masterminds/squirrel/blob/bb2d02daec8b134e317099d88c466e1bd4ccf67d/select_test.go#L173

**Comment by veqryn** [comment]
Instead of having an awkward workaround, could we have a new function for this, such as `JoinSelect`?
