### ISSUE TITLE
Support "REPLACE INTO" syntax

### ISSUE THREAD

**Issue by Shamus03** [Masterminds/squirrel#201]
Currently it is impossible to use "REPLACE INTO".  I've worked around it by using `strings.Replace(stmt, "INSERT INTO", "REPLACE INTO", 1)` but that's not ideal.

I was thinking about adding an optional string field to `insertData` that specifies an override for the "INSERT" clause.  What do you think?

**Comment by lann** [comment]
I have generally tried to avoid adding dialect-specific code, but since this is such a (relatively) common one and there is no great workaround, I [added a `Replace` function](../commit/b924fed91bf30ef4ae18d07b7bf9d7f66ebf27bb). Don't tell anyone I broke my own rule.
