### ISSUE TITLE
Update jsonb field using squirrel in postgres

### ISSUE THREAD

**Issue by saaqibz** [Masterminds/squirrel#208]
Has anyone successfully updated a jsonb field in postgres? I haven't seen any documentation for this and I've tried to do it directly but am running into a bit of issues.

**Comment by prochac** [comment]
What SQL query are you trying to achieve?

**Comment by saaqibz** [comment]
Hi Tomas,

Thanks for taking a look. maybe something like this:
```
UPDATE my_stuff
SET json_col = jsonb_set(json_col, '{stuffName}', to_jsonb($1::text))
WHERE user_id = $2 AND id = $3 AND deleted IS NULL`,
```

**Comment by slnt** [comment]
@saaqibz 

To get that SET you can use an `sq.Expr`

```go
psql.Update("my_stuff").
	Set("json_col", sq.Expr("jsonb_set(json_col, '{stuffName}', to_jsonb(?::text)", "arg")).
	Where(sq.Eq{"user_id": "..."}).
	Where(sq.Eq{"id": "..."}).
	Where("deleted IS NULL")
```

**Comment by lann** [comment]
Squirrel has been effectively inactive (or more optimistically, "complete") for a while now. I have updated the README to reflect this fact.
