### ISSUE TITLE
Support subquery in FROM operator

### ISSUE THREAD

**Issue by umisama** [Masterminds/squirrel#21]
I want to create query like `SELECT * FROM (SELECT Max(someval), modified FROM sometable group by someval ) WHERE modified>?`, but I can't find any way because squirrel is not supporting subquery in `FROM` operator.

I have a idea to support subquery, see following code.

``` go
q, _, _ := sq.Select("*").FromSubQuery(
        sq.Select("Max(someval)", "modified").
                From("sometable").
                GroupBy("someval")).
        Where("modifyed > ?", t)
```

define:

```
func (b SelectBuilder) FromSubQuery(SelectBuilder) SelectBuilder
```

What do you think so? If you agree on this idea, I'll create patch and send PR.
Thanks!

**Comment by elgris** [comment]
Hi guys! You can also check alternative with no additional builders implementation ;)
https://github.com/elgris/sqrl
If it looks good, I can prepare PR for squirrel.

**Comment by atombender** [comment]
I also expected `Where` and `Join` to accept subqueries. E.g.:

```go
sqlBuilder.
  Select("id").
  From("documents").
  Where(squirrel.Eq("id": sqlBuilder.
  	Select("source_id").
  	From("refs").
  	Where(squirrel.Eq{"target_id", ids})))
```

This issue hasn't received any love since 2014. Seems Squirrel doesn't have much activity.

**Comment by cmshnrblu** [comment]
Any fix for SelectFrom since this was closed? I am having problems passing arguments using select from and postgres. I keep getting pq: got 1 parameters but the statement requires 0. Workarounds would be satisfactory as well. Thanks!

**Comment by ranfdev** [comment]
If you use squirrel and postgres, you probably have something like this
```go
var psql = sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
```
in your code.

Don't use that when writing code which uses subqueries. Instead, simply use squirrel directly.
```go
query := sq.Select()....
```
Then, just before calling `.ToSql()`, convert the placeholders:
```go
sql, args, err := query.PlaceholderFormat(sq.Dollar).ToSql()
```
