### ISSUE TITLE
CockroachDB support

### ISSUE THREAD

**Issue by fracasula** [Masterminds/squirrel#211]
Hi there, are there any plans to support CockroachDB?

If not, would you guys consider Pull Requests to add support for instructions like `RETURNING <col_name>` or it's out of the question?

https://www.cockroachlabs.com/docs/stable/insert.html#insert-and-return-values

Thanks!

**Comment by prochac** [comment]
What about [Suffix](https://godoc.org/github.com/Masterminds/squirrel#InsertBuilder.Suffix)? 
https://play.golang.org/p/UOfN0ELR8zM

**Comment by fracasula** [comment]
What about [UPSERT](https://www.cockroachlabs.com/docs/stable/upsert.html)s?

**Comment by lann** [comment]
As a workaround, you could use `Suffix` to specify an [`ON CONFLICT`](https://www.cockroachlabs.com/docs/stable/upsert.html#how-upsert-transforms-into-insert-on-conflict) clause for an `INSERT`.

**Comment by lann** [comment]
Squirrel has been effectively inactive (or more optimistically, "complete") for a while now. I have updated the README to reflect this fact.
