### ISSUE TITLE
Cannot `go mod tidy` with squirrel imported

### ISSUE THREAD

**Issue by slnt** [Masterminds/squirrel#212]
I am having issues running `go mod tidy` while having `squirrel` imported.

```
xyx.com/mypackage/foo/bar imports
        github.com/Masterminds/squirrel tested by
        github.com/Masterminds/squirrel.test imports
        github.com/mattn/go-sqlite3: module github.com/mattn/go-sqlite3@latest found (v2.0.0+incompatible), but does not contain package github.com/mattn/go-sqlite3
```

**Comment by slnt** [comment]
Workaround:

Do a `go get -v -u github.com/mattn/go-sqlite3@v1.10.0`

**Comment by lann** [comment]
This is annoying. Suggestions welcome, but I suspect the only real way to fix this is to move integration tests into their own (sub-) module.

**Comment by lann** [comment]
https://github.com/Masterminds/squirrel/commit/eb15de201f5663d89a3db5c53855f0106a42f441
