### ISSUE TITLE
Add support for custom `BaseRunner` with `RunWith`

### ISSUE THREAD

**Issue by slnt** [Masterminds/squirrel#213]
Allow for custom implementations of the `squirrel.BaseRunner` to be used with the `.RunWith` function for `SelectBuilder`, etc.

While attempting to use this library, I tried to pass a custom wrapper that we have of `*sql.DB`, which adds some extra stuff for us such as logging of our requests. However, I was met with the error message:

```
"cannot run; no Runner set (RunWith) ...
```

I was trying to run via `query.RunWith(myCustomDB).Query()`. Debugging I found that my DB was not nil, as I though it might somehow be, and the library was just refusing to use it.

I find this runs counter to how I would expect the library to work. I'd expect that so long as I implement the interface, the library would be able to use the implementation I provide, similar to functions in `ioutils` that accept `io.Writer`s or `io.Readers`.

This seems to be an issue that has been encountered before in #86, however this task would be slightly more broad in accepting _any_ implementation of `squirrel.BaseRunner`.

**Comment by lann** [comment]
Well thats just broken. I clearly *tried* to make it work, and it clearly *doesn't*. Should be fixed by #214

**Comment by lann** [comment]
https://github.com/Masterminds/squirrel/commit/dde2d7b36e45910a739f372e177727c3803a2fa2

**Comment by slnt** [comment]
Thanks for the quick response time @lann!
