### ISSUE TITLE
Add `SuffixExpr` function to `SelectBuilder`

### ISSUE THREAD

**Issue by slnt** [Masterminds/squirrel#216]
I would like to do something like this:

```golang
sq.
	Select("col").
	From("table").
	LimitSelect(sq.
		Select().
		Column(sq.Case().
			When("x = y", 10).
			Else(0).From("table"),
		),
	)
```

The SQL that would be generated by this would look something like:

```sql
SELECT col FROM table 
LIMIT (
  SELECT CASE WHEN x = y THEN 10 ELSE 0 END FROM table
)
```

This is valid for at least Postgres, as I'm able to run a query like this, however I am not sure about other flavors.

I can sort of work around this with `.Suffix` but it makes me rather sad to have to do it that way 😢

**Comment by slnt** [comment]
https://github.com/Masterminds/squirrel/pull/217/

**Comment by slnt** [comment]
@lann would love it if you could take a look at this when you have time 😃

**Comment by lann** [comment]
I've been pondering whether to accept this. I'm inclined not to, since this appears to be Mysql-specific and I have resisted adding SQL-dialect-specific syntax in the past in an attempt to manage complexity.

**Comment by slnt** [comment]
Should it be left to the user to determine what is or is not valid SQL for their given dialect? It is probably impossible for the library to enforce always correct SQL syntax. 

Perhaps adding a note to the functions comment that it would only work if your SQL dialect supports it would be sufficient?

**Comment by slnt** [comment]
Alternatively @lann, what are your thoughts on this?

```go
func (b SelectBuilder) SuffixExpr(expr Sqlizer) { 
  //... 
}

// usage:
func foo() {
	sq.
		Select("col").
		From("table").
		SuffixExpr(sq.ConcatExpr(
			"LIMIT (",
			sq.
				Select().
				Column(sq.Case().When("x = y", 10).Else(0)).
				From("table"),
			")",
		))
}
```

Current usage of `.Suffix` seems to require that you build and `.ToSql` first.

**Comment by lann** [comment]
I'd be happy to accept `SuffixExpr`.

**Comment by slnt** [comment]
#220
