### ISSUE TITLE
is there a way to generate a sql without placeholder?

### ISSUE THREAD

**Issue by axiaoxin** [Masterminds/squirrel#222]

**Comment by elmawardy** [comment]
That's really a good idea why don't we just inject values instead of placeholders ,then get the SQL including the values , this should be an obvious feature that saves tons of time specially for beginners.

**Comment by lann** [comment]
Squirrel has been effectively inactive (or more optimistically, "complete") for a while now. I have updated the README to reflect this fact.

**Comment by lann** [comment]
> That's really a good idea why don't we just inject values instead of placeholders ,then get the SQL including the values , this should be an obvious feature that saves tons of time specially for beginners.

I can't tell if you are being sarcastic. If not, please read up on "SQL injection".
