### ISSUE TITLE
Proposal for adding dialect specific syntax features

### ISSUE THREAD

**Issue by slnt** [Masterminds/squirrel#223]
It has occurred to me that now that `PrefixExpr` and `SuffixExpr` are in the library, there is a fairly nice way to add some dialect specific functionality.

Taking Postgres for example, some useful functions that many others have proposed are `WITH` query prefixes, as well as `RETURNING`  suffixes. To add in this functionality I would propose that a  `"dialect/postgres"` subpackage is added containing functions such as:

```go
func Alias(name string, expr sq.Sqlizer) aliasExpr {}
func With(aliases ...aliasExpr) sq.Sqlizer {}
func Returning(columns ...string) sq.Sqlizer {}

type aliasExpr struct {
	name string
	expr sq.Sqlizer
}
```

Then, to generate SQL such as:

```sql
WITH moved_rows AS (
    DELETE FROM products
    WHERE
        "date" >= '2010-10-01' AND
        "date" < '2010-11-01'
    RETURNING *
)
INSERT INTO products_log
SELECT * FROM moved_rows;
```

one could do:

```go
import (
	sq "github.com/Masterminds/squirrel"
	sqpg "github.com/Masterminds/squirrel/dialect/postgres"
)

func moveRows() {
	sq.Insert("products_log").
	PrefixExpr(
		sqpg.With(sqpg.Alias("moved_rows", 
			sq.Delete("products").
			Where("\"date\" >= '2010-10-01'").
			Where("\"date\" >= '2010-10-01'").
			SuffixExpr(sqpg.Returning("*"))
		)),
	).
	Select(sq.Select("*").From("moved_rows"))
}
```

I think this would add clarity to users that these are postgres specific features, and will let the features be added without making any weird breaking changes to the API.

Thoughts?

**Comment by slnt** [comment]
@lann if you're cool with this design I'll start plugging away at it soon, for some postgres features at least.

**Comment by lann** [comment]
I have done some work toward a "squirrel 2" that would simplify this kind of thing, but I can't promise I'll finish it. I'd be happy to accept this addition.

**Comment by lann** [comment]
Squirrel has been effectively inactive (or more optimistically, "complete") for a while now. I have updated the README to reflect this fact.
