### ISSUE TITLE
fix where 

### ISSUE THREAD

**Issue by talpa** [Masterminds/squirrel#232]
please fix 

```
query.Where( 
         sq.Eq{"s.id":11}, //1 
         sq.Or{sq.Eq{"s.state":state }, //2 
        sq.Eq{"s.date":date}})
```

NOW
--------
`WHERE s.id = 11;`

After Fix
---
`WHERE si.id = 11 AND (s.state = 'state' OR  s.date = date);`

**Comment by lann** [comment]
`Where` doesn't accept multiple expressions like that. They only time extra args are considered is when the first argument is a string, e.g. `Where("x = ?", 1)`. Its a weakness of the API design, but I'm not sure it can be fixed now backward-compatibly.

**Comment by lann** [comment]
Another way to get what you want:
```go
query.Where( 
    sq.And{sq.Eq{"s.id":11}, 
           sq.Or{sq.Eq{"s.state":state }, 
                 sq.Eq{"s.date":date}}})
```

though if the structure of the query is fixed, sometimes plain SQL is the easiest to read:
```go
query.Where("si.id = ? AND (s.state = ? OR s.date = ?)", 11, state, date)
```
