### ISSUE TITLE
Dynamic where clauses

### ISSUE THREAD

**Issue by osherElmakayes** [Masterminds/squirrel#234]
I am trying to do that: 
builder.Where("? ? ? ",Column,Operator, value)
I have also tried to do the same thing where I only pass the value as param
builder.Where("Column Operator",value) -- where the column and operator are the real values and not like that for example :  ("t = ",value) (Value is string)
Nothing seems to work all I get is "" back,
I was wondering if there is any way to make a dynamic where clauses without the Eq(),notEqual etc.. 
thanks.

**Comment by lann** [comment]
Only values (not columns or operators) work with placeholders; this isn't specific to squirrel but how SQL generally works. 

You should be able too do something like this:
```go
Where(fmt.Sprintf("%s %s ?", column, operator), value)
```

Be careful that you don't allow any user input in `column` or `operator` as that would likely be a security vulnerability.

**Comment by osherElmakayes** [comment]
Thanks for the tip, I found out that the problem was not using Select before building the where section, which I opened another ticket for.
Thanks a lot.
