### ISSUE TITLE
Is there a way to build Query without the Select statement?

### ISSUE THREAD

**Issue by osherElmakayes** [Masterminds/squirrel#235]
If I want to build the Where clauses and then to attach it to a select statement after that is there a way to do that? Right now it seems to always return a "" if I do that.

An example of the flow would be:

filterQuery = buildFilters(filters) -> Returns only the Where section
filterquery.PrefixExpr(selectSection) (The reason I do that is because select might be using index and another thing that I do not know while building the filters)...
or selectStatement.suffixExp(filterQuery)

P.S
I haven't found a nice way of using index in the query builder so if there is one would be really nice.

**Comment by adrianotadao** [comment]
hey @osherElmakayes, have you found the answer to your question?
