### ISSUE TITLE
optional where condition

### ISSUE THREAD

**Issue by coolyrat** [Masterminds/squirrel#236]
Hi, I have a search query that might have some optional conditions. eg. may pass name paramter for searching, or a type that is equal to an integer. It would be useful to have something like:

```go
builder.Where(sq.IfNotBlank{"name": param.Name}, sq.IfNotNull{"type":param.type}). ToSql()
```

if name is not blank:
```sql
select * from tbl where name = 'xxx' and type = 1
```

if name is blank:
```sql
select * from tbl where type = 1
```

**Comment by coolyrat** [comment]
#238

**Comment by sugatpoudel** [comment]
@coolyrat This seems like a really neat idea however would it be more general to have a `ConditionalWhere` method such that the first argument could be a predicate that needs to pass before the where can be applied.

The method could look something like this
```go
func (b SelectBuilder) ConditinalWhere(condition func() bool, pred interface{}, args ...interface{}) {
    if condition() {
        return b.Where(pred, args...)
    }
    return b
}
```

**Comment by coolyrat** [comment]
@sugatpoudel there's something different. You want to expose the condition outside the where.  And I want to check the arg is nil or zero value from the inside.

**Comment by sugatpoudel** [comment]
That’s true however I think having the predicates be part of the squirrel codebase would tightly couple checkers with the query builders such that anytime a user wanted a new predicate, a pull request would need to be made. 

Also the method signature current use the predicates for conditions that are actually part of the sql query so the query builders would need to differentiate between the normal and `if` predicates. 

With the `ConditionalWhere` approach, the conditional complexity is with the caller and they can choose to use any arbitrary logic including if the argument was null or empty. 

```go
builder.ConditionalWhere(param.Name != nil && param.Name != “”, sq.Eq{“name”: param.Name})
```

The conditional could be extracted into a helper to make this more readable.
