### ISSUE TITLE
How to do a FULL OUTER JOIN?

### ISSUE THREAD

**Issue by teresa-recursion** [Masterminds/squirrel#237]
I see support for LEFT JOIN, RIGHT JOIN, and JOIN but no way to do a FULL OUTER JOIN.  Is this something I could/should create a PR to add?

**Comment by lann** [comment]
`JoinClause` lets you specify custom join types:

```go
JoinClause("FULL OUTER JOIN table2")
```

**Comment by teresa-recursion** [comment]
Perfect, thank you!
