### ISSUE TITLE
DISTINCT ON (postgres only)

### ISSUE THREAD

**Issue by jsimnz** [Masterminds/squirrel#24]
The API currently includes DISTINCT SQL command, however postgres supports a DISTINCT ON command which allows you to define a column to compute distinctiveness, but still select columns as you usually would.

Is there any plans for this, or, if I submit a PM, would this be an accepted feature?

**Comment by tg** [comment]
+1 on this. I understand there's currently no way to do `select distinct on` using squirrel? (other than manually hacking `ToSQL()` output)

**Comment by mbinette** [comment]
I was just looking for DISTINCT ON support and saw the latest version has the .Options feature which can be used. The nicety of using a namespaced DistinctOn would be that it could take a slice of column names like .Select does to build the DISTINCT ON (...cols) text. 

But possibly the best option is to keep it out of Squirrel and just write your own function that takes a slice of columns names and returns the specific text. So you would have

`.Select("col1","col2","col3").Options(MyPostgresqlPkg.DistinctOn("col1","col2"))`

Maybe a directory off of Masterminds/Squirrel for each db dialect that people can contribute Options extensions for or a completely different repo?
