### ISSUE TITLE
Feature request: serialize builders to []byte, and vice versa

### ISSUE THREAD

**Issue by ddevault** [Masterminds/squirrel#245]
I would like to be able to convert a builder to a []byte, and convert a []byte into a builder. The use-case is implementing cursors for an API: I want to take a given query, serialize it to []byte, encrypt it and base64 it, then return it to the user. They give the same data back to me, I decode, decrypt, and deserialize it, then update it to fetch the next page of results and generate a new cursor to send back.

**Comment by lann** [comment]
I think this is fundamentally impractical for squirrel as it is currently architected; it would require (de)serializing arbitrary types in the general case and "lots" of types even in common cases.

An alternative approach for your use case would be to wrap the appropriate params in a struct and then intercept those params immediately before execution; something like (totally untested; definitely doesn't compile):

```go
type pageParam struct {
    Name string
    Value interface{}
}

func (pp pageParam) ToSql() (string, []interface{}, error) {
    return "?", []interface{pp.Value}, nil
}

func extractPageParams(args []interface{}) map[string]interface{} {
    m := make(map[string]interface{})
    for _, arg := range args {
        if pp, ok := arg.(pageParam) {
            m[pp.Name] = pp.Value
        }
    }
    return m
}

func applyPageParams(args []interface{}) // inverse of extract
```

These could either be used in the appropriate call sites or be called automatically by a custom implementation of `squirrel.Runner`.

I have other even hackier ideas if you're interested. Happy to spend time on this given that I'm writing this from within sway :smile:

**Comment by ddevault** [comment]
Currently I settled for this:

https://git.sr.ht/~sircmpwn/git.sr.ht/tree/graphql/api/graph/model/cursor.go

Then I'm just going to manually build the necessary queries to factor in these details at the usage site. Would rather not push something hacky into production.

Glad you're enjoying sway :)
