### ISSUE TITLE
Join Table 'specified more than once'

### ISSUE THREAD

**Issue by adrianotadao** [Masterminds/squirrel#248]
Hi there,

Is there a way of checking if a specific `Join` already exists before using `psql.Select("x.*").From("x").Join()`?

I'm getting the error `specified more than once` xD

**Comment by lann** [comment]
There is not. You could do it in a rather hacky manner with something like:
```go
sql, _, err := b.ToSql()
if err == nil && !strings.Contains(sql, "JOIN <whatever>") {
    b = b.Join(...)
}
```

**Comment by adrianotadao** [comment]
@lann okay, thx!
