### ISSUE TITLE
OrderByClause does not work as expected

### ISSUE THREAD

**Issue by evanfuller** [Masterminds/squirrel#249]
If I write a query like the following:

```		
                requestTimeColumn := "request_time"
                query, args, err := squirrel.Select(
			requestTimeColumn,
			columnA,
			columnB,
		).
		From("my-table").
		OrderByClause("? DESC", requestTimeColumn).
		ToSql()

```

The result value of the returned `query` is `SELECT request_time, columnA, columnB FROM my-table ORDER BY ? DESC`, and `args` contains the placeholder `request_time`.

However, the actual data that is returned does not obey the ordering constraint, so it would seem that squirrel is not properly evaluating this placeholder arg. Generally speaking, I know that SQL does not allow for placeholders to appear in the "order by" clause, so I believe the query builder needs to substitute this value before returning. I would expect my output to be `query == "SELECT request_time, columnA, columnB FROM my-table ORDER BY request_time DESC"`, and `args` should be empty.

**Comment by lann** [comment]
Squirrel does not process placeholders; that is done by your database (or database driver). If you want a dynamic column name you have to build the string, e.g. `OrderBy(requestTimeColumn + " DESC")`

**Comment by evanfuller** [comment]
So how is the `OrderByClause()` function supposed to be used then? What are the args that it takes?

**Comment by lann** [comment]
It isn't used very often. An example might be something like `OrderByClause("COALESCE(sort_pos, ?)", defaultSortPos)`
