### ISSUE TITLE
Support with multiple tenant

### ISSUE THREAD

**Issue by tranhoangvuit** [Masterminds/squirrel#250]
I have an application with multiple tenant and I just want limit on application level. So that means in every query I need to add `tenant_id = ?`. So do we have any way to support it for both case insert(auto add tenant_id in insert query) and `SelectBuilder`, `UpdateBuilder`, `DeleteBuilder` with `where tenant_id=?`.
Thank you so much.

**Comment by lann** [comment]
You can now: ae9fdddf160b6c3f6dbd9c38405a06640e3633b3

```go
sb := StatementBuilder.Where("x = ?", 1)
sb.Select("y") // SELECT y WHERE x = 1
```

**Comment by tranhoangvuit** [comment]
Wow. Thank you so much for you quick update.
