### ISSUE TITLE
How to create insert sql start with "INSERT IGNORE INTO"?

### ISSUE THREAD

**Issue by anotherGoogleFan** [Masterminds/squirrel#253]
I read the document but do not found the method. 
Is there a way to create insert sql start with "INSERT IGNORE INTO"?

**Comment by lann** [comment]
`IGNORE` is a language extension, and is supported by the generic `Options` method: https://godoc.org/github.com/Masterminds/squirrel#InsertBuilder.Options

**Comment by anotherGoogleFan** [comment]
@lann   Thanks for reply.  Very useful for me.
