### ISSUE TITLE
Args not bound on WHERE clause

### ISSUE THREAD

**Issue by Segflow** [Masterminds/squirrel#255]
I tried to use this
```
val := "val"
base := sq.Select("*").From("c")
where := base.Where("s = ?", val)
sql, _, _ := where.ToSql()
```

I expected to final SQL to be 
```
SELECT * FROM c WHERE s = "val"
``` 

but instead I got 

```
SELECT * FROM c WHERE s = ?
```

Anything I'm doing wrong?

**Comment by lann** [comment]
The argument value is in one of the return values that your code snippet ignored: `sql, args, _ := where.ToSql()`

**Comment by Segflow** [comment]
Is there any way to generate the final SQL query? with values bounds

**Comment by lann** [comment]
You can use the `DebugSqlizer` function to preview it, but as the name implies that is only for debugging. Is there a specific reason you cannot use the separate arguments as usual?

**Comment by Segflow** [comment]
I'm not sure if I'm using squirrel for the correct purpose, but my need is this:

We need use CosmosDB SQL API, and all we want is generate a final SQL query which we can sent via http the Azure endpoints.

**Comment by lann** [comment]
Ah, I am not very familiar with CosmosDB. From a quick look, it appears to not be a RDBMS, so it probably does not work with Go's standard `db/sql` library. Squirrel is designed around the `db/sql` interfaces, so it will not support CosmosDB very easily.

You could probably adapt Squirrel to work with it by combining the builtin `squirrel.AtP` PlaceholderFormat and building up a parameterized query as described here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-parameterized-queries

If you are not already familiar with "SQL injection" attacks, it is important to read about them before attempting to use SQL with any kind of user input. It is one of the primary reasons why we do not normally have values inserted into the SQL string automatically. Here is an article about SQL injection in the context of CosmosDB: https://michaelhowardsecure.blog/2019/03/05/cosmosdb-and-sql-injection/

**Comment by Segflow** [comment]
We actually wanted to use a query generator so that we can provide an interface to create queries and sanitize data to prevent SQL Injection like attacks. 

Thank you for the fast replies, really appreciate it.
