### ISSUE TITLE
nest result into Go slice?

### ISSUE THREAD

**Issue by sefo** [Masterminds/squirrel#267]
I have a struct like
```
type UserComments struct {
	User `json:"user" db:"user,omitempty"`
	Comments []*Comment `json:"comments" db:"comments,omitempty"`
}
```
In the DB (postgres) I have a user table, a comment table and an association table called user_comments (containing only user_id and comment_id)

I'd like to scan the result of a query into a slice of UserComment.

I've tried nesting the array of comments using sqlx but it doesn't support nested structures: https://github.com/jmoiron/sqlx/issues/231

I'm moving slowly towards using squirrel everywhere but I couldn't think of a way to make this nesting happen.

Can squirrel give me a result like this?

```
users: [
  { id: 1, name: 'john', comments: [ {...}, {...} ] },
  { id: 2, name: 'jim', comments: [ {...}, {...} ] },
  { id: 3, name: 'jane', comments: [ {...}, {...} ] }
]
```

**Comment by sanggonlee** [comment]
@sefo I think you can achieve that using json functions in postgres. So something like
```go
q, args, err := sq.Select("*").
  Columns("COALESCE(json_agg(comment)) FILTER (WHERE comment.id IS NOT NULL), '[]') AS comments")
  From("user").
  LeftJoin("comment ON comment.user_id = user.id").
  GroupBy("user.id").
  ToSql()
```
