### ISSUE TITLE
Help needed for conditional WHERE clause creation

### ISSUE THREAD

**Issue by fallais** [Masterminds/squirrel#273]
Hello, I am trying to create a conditional WHERE clause based on a struct that I defined myself for a REST API.

The code below is, of course, not working. But I can't see how to achieve this..
Could you please help.. ?

The need is simple, is something is provided in the filter, I need to add it in the global _AND_ structure.

```go
func (r *incidentRepository) buildFilter(filter *repositories.IncidentSearchFilter) interface{} {
	if filter != nil {
		clauses := sq.And{
			sq.Eq{"1": "1"},
		}

		if !filter.From.IsZero() {
			clauses.LtOrEq{
				"created_at": filter.From,
			}
		}

		if len(strings.TrimSpace(filter.Title)) > 0 {
			clauses["title"] = filter.Title
		}

		return clauses
	}

	return nil
}
```

Thanks a lot...

**Comment by fallais** [comment]
I discovered that the **AND** and **OR** clauses are just arrays. So that I can do this :

```go
clauses := squirrel.And{
	squirrel.Eq{"1": "1"},
}

if len(strings.TrimSpace(filter.Title)) > 0 {
	clauses = append(clauses, squirrel.Eq{
		"title": filter.Title,
	})
}

if !filter.From.IsZero() {
	clauses = append(clauses, squirrel.GtOrEq{
		"created_at": filter.From,
	})
}
if !filter.To.IsZero() {
	clauses = append(clauses, squirrel.LtOrEq{
		"created_at": filter.To,
	})
}
```

This is perfect !
Hope that I will help someone one day :)

**Comment by lann** [comment]
Also, `Eq` is just a map, and it's items get ANDed together

**Comment by fallais** [comment]
@lann : Hum.. I see.. So this below would be the same ?

```go
clauses := squirrel.Eq{ }

clauses = append(clauses, squirrel.Eq{
	"1": "1",
})

if len(strings.TrimSpace(filter.Title)) > 0 {
	clauses = append(clauses, squirrel.Eq{
		"title": filter.Title,
	})
}

if !filter.From.IsZero() {
	clauses = append(clauses, squirrel.GtOrEq{
		"created_at": filter.From,
	})
}
if !filter.To.IsZero() {
	clauses = append(clauses, squirrel.LtOrEq{
		"created_at": filter.To,
	})
}
```

**Comment by lann** [comment]
It just means you can update the Eq directly, like:

```go
eq := sq.Eq{}
if foo != "" {
    eq["foo"] = foo
}
```

It doesn't help much in your specific example but it comes in handy.

**Comment by lann** [comment]
Separately, you don't need the "1=1" expression in your example; `sq.And` resolves to true when empty for exactly this reason.
