### ISSUE TITLE
PostgreSQL table names

### ISSUE THREAD

**Issue by Arideno** [Masterminds/squirrel#276]
I am trying to run this code:  `
query, args, _ := psql.Select("*").From("user").Where(sq.Eq{"id": id}).Limit(1).ToSql()
`
But driver does not want to execute this query because table name should be in quotes. This variant does work but isn’t there a way not to write quotes directly?
`
query, args, _ := psql.Select("*").From("\"user\"").Where(sq.Eq{"id": id}).Limit(1).ToSql()
`

**Comment by lann** [comment]
What driver? What's the exact error? Postgres does not generally require simple table names to be quotes.

**Comment by Arideno** [comment]
@lann as I understood, user is reserved name and it says that there are no such columns in this table. I use pgx.

**Comment by lann** [comment]
Ah, that makes sense. No, there is not currently any way to automatically quote table names. You could at least avoid the backslashes by using a raw string literal: ``From(`"user"`)``
