### ISSUE TITLE
Question: How does Squirrel help with SQL injection?

### ISSUE THREAD

**Issue by ppipada** [Masterminds/squirrel#278]
Hello,

Is there any guidance/docs on how squirrel helps with avoiding SQl injection? Or is it the case that it does not fit its goals?
Any info on this would be great.

**Comment by lann** [comment]
Squirrel was originally built to make it easier to build complex queries while avoiding sql injection. Most of its features generate SQL placeholders and a separate list of arguments. These are passed separately to your database driver which should generally prevent sql injection.

That said, squirrel _allows_ raw sql in a number of places, so it is certainly possible to write vulnerable code with it. When in doubt, you can check the first two return values of e.g. `sql, args, err := myStmt.ToSql()`; if you see user input in the `sql` string you may have a problem, but if user input only appears in `args` then you are probably safe.

**Comment by ppipada** [comment]
Thank you for your help :)
