### ISSUE TITLE
Add BETWEEN ? AND ? in Squirrel

### ISSUE THREAD

**Issue by gustavohmsilva** [Masterminds/squirrel#284]
Hi all,

Currently, we have been using Expr function to generate a SQL with BETWEEN, or, depending on the circunstances, we've been using a combination of And{} and LtOrEq{} and GtOrEq{} to reproduce the same thing. This is tho somewhat janky as the first is against the idea of Squirrel (minimize SQL written in Go Codebase) and the second, overly complicated.

Would it be worth consideration by the mantainers to develop squirrel.Between{} in Squirrel?

**Comment by Pawda** [comment]
Hi @gustavohmsilva, 

As @lann replied here: #180 

>  You can get the same effect with e.g. sq.Expr("x BETWEEN ? AND ?", low, high)


Works fine, and the other way around too: 
`sq.Expr("? BETWEEN col_min AND col_max", x)`
