### ISSUE TITLE
Migrate to pgx

### ISSUE THREAD

**Issue by robsonpeixoto** [Masterminds/squirrel#293]
`github.com/lib/pq` is a deprecated lib https://github.com/lib/pq#status.
Maybe is a god idea move to github.com/jackc/pgx

**Comment by arpanetus** [comment]
I guess `sq.StatementBuilder.PlaceholderFormat(sq.Dollar)` already does that for query generation as such

**Comment by mfridman** [comment]
@robsonpeixoto (or others) did you ever get a nice solution here?
