### ISSUE TITLE
Error 1054: Unknown column '$1' in 'where clause'

### ISSUE THREAD

**Issue by madasatya6** [Masterminds/squirrel#300]
id parameter where is unreadable 

this my code :

```
import "log"
import sq "github.com/Masterminds/squirrel"

func main(){
    var Builder = sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
    var id = 2
    var Table = "setting"

    queryText := Builder.
		Select("*").
		From(Table)

    sql, _, _ := queryText.
		Where(sq.Eq{"id":id}).
		Limit(1).
		ToSql()

    log.Println(sql)
}
```

the above code generates sql : "**SELECT * FROM setting WHERE id = $1 LIMIT 1**", so the id is not read

**Comment by lann** [comment]
ToSql returns three values. The second value (assigned to _ in your code) is a list of arguments that correspond to the placeholders in the generated SQL. This list of arguments is passed to the database separately from the SQL; see e.g. https://pkg.go.dev/database/sql#DB.Query
