### ISSUE TITLE
Where array field contains element?

### ISSUE THREAD

**Issue by mrkagelui** [Masterminds/squirrel#305]
Hi, I'm using PostgreSQL with a field of type "TEXT[]", my query needs to find records with this field containing a specific input string, is this provided? Or should I create my own structure implementing sqlizer or some other interface?

**Comment by lann** [comment]
Any custom query condition should be possible with the `Expr` function, e.g. (untested) `.Where(sq.Expr("? = ANY (haystack_column)", needle))`

**Comment by mrkagelui** [comment]
I see, thank you for the reply!
