### ISSUE TITLE
Bind values from struct tag

### ISSUE THREAD

**Issue by lucasmdomingues** [Masterminds/squirrel#307]
Would it be valid to insert a struct so that it is possible to assemble the query? Something that from a `db:` tag, for example, read all the fields to assemble the query? Similar to what sqlx does in `Named` functions

Example:

```
type User struct {
    ID int `db:"id"`
    Email string `db:"email"`
}

sq.Insert("users").Columns(&User{}).Values(&user).ToSql()
// INSERT INTO users(id,email) VALUES(:id,:email);
```

**Comment by lann** [comment]
Out of scope for this project. See e.g.: https://github.com/d-tsuji/awesome-go-orms
