### ISSUE TITLE
How to WHERE name = $1 OR $1 IS NULL ?

### ISSUE THREAD

**Issue by oussamm** [Masterminds/squirrel#310]
Hello,
I am having hard time to just write a where clause with an optional parameter.

How could I accomplish this :
```sql
WHERE name = $1 OR $1 IS NULL
```
I would like to add multiple optional where clauses.

Really need help for that

**Comment by oussamm** [comment]
I just realized that solution is a bad pattern, if someone could confirm me or give me an alternative, that could be great.

**Comment by lann** [comment]
One option is to do it in Go:

```go
stmt = squirrel.Select("*").From("table")
if name != nil {
    stmt = stmt.Where("name = ?", name)
}
```

**Comment by oussamm** [comment]
I will try this, I hope it will be readable :D

**Comment by liuchamp** [comment]
> One option is to do it in Go:
> 
> ```go
> stmt = squirrel.Select("*").From("table")
> if name != nil {
>     stmt = stmt.Where("name = ?", name)
> }
> ```

Whether this feature is supported or not, currently it is not possible to add conditions  .
![image](https://user-images.githubusercontent.com/25866957/158790166-a2f85846-d9d0-491d-8364-498e6120cefe.png)
![image](https://user-images.githubusercontent.com/25866957/158790241-d6cea7d1-5832-4a66-85a6-eda43871da9e.png)

**Comment by oussamm** [comment]
Ok thank you for your reply. 
I will close the issue
