### ISSUE TITLE
How build subquery in SELECT?

### ISSUE THREAD

**Issue by mayken** [Masterminds/squirrel#319]
How build query: `SELECT DISTINCT t1.id, t1.name, (SELECT COUNT(id) FROM t2 WHERE t2.parent_id = t1.id) as t2_count FROM t1.`

I do it but not working: 
```
var psql = sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
var subQuery sq.SelectBuilder

subQuery = psql.Select("COUNT(id)").From("t2").Where(sq.Eq{"t2.parent_id": "t1.id"})

queryBuilder := psql.
	Select("t1.id", "t1.name").
	FromSelect(subQuery, "t2_count").
	Distinct().
	From("t1")
```

Result: `SELECT DISTINCT t1.id, t1.name FROM t1`

**Comment by toudi** [comment]
I believe the order is significant. I changed your code slightly like so:

```	queryBuilder := psql.
		Select("t1.id", "t1.name").
		From("t1").
		FromSelect(subQuery, "t2_count").
		Distinct()
```

and it produces the expected SQL

**Comment by mayken** [comment]
> aha! after a minute of debugging I found out the reason. You need to change your code slightly:
> 
> ```go
> 	var psql = sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
> 	var subQuery sq.SelectBuilder
> 
> 	subQuery = psql.Select("COUNT(id)").From("t2").Where("t2.parent_id = t1.id")
> 
> 	queryBuilder := psql.
> 		Select("t1.id", "t1.name").
> 		Column(sq.Alias(subQuery, "t2_count")).
> 		From("t1").
> 		Distinct()
> 
> 	query, err, args := queryBuilder.ToSql()
> 	fmt.Printf("query=%v; err=%v; args=%v", query, err, args)
>         // output: 
>         // query=SELECT DISTINCT t1.id, t1.name, (SELECT COUNT(id) FROM t2 WHERE t2.parent_id = t1.id) AS t2_count FROM t1; err=[]; args=<nil>
> ```
> 
> (so: Column(Alias) instead of just FromSelect). FromSelect seems to be used when you want to select from a subquery.
> 
> there are more examples that you can find here:
> 
> https://github.com/Masterminds/squirrel/blob/master/select_test.go
> 
> cheers!

Exactly what is needed!) Thanks!
