### ISSUE TITLE
The ordering of the Eq keys matters to the db index 

### ISSUE THREAD

**Issue by c9s** [Masterminds/squirrel#321]
Thank you for sharing this beautiful library.

I saw `squirrel` sorted the Eq keys by sort.String internally,

However the ordering of the conditions matters to the mysql index.

For example, given an existing index `index(b,a)`:

```
WHERE b > 1 AND a < 10
```

The above where clause can use that index.

If we sort the conditions alphabetically,

```
WHERE a < 10 AND b > 1
```

The index won't be effected.

**Comment by c9s** [comment]
or maybe you mean we have to write the conditions in the following syntax?

```
		Where(sq.And{
			sq.Eq{"symbol": symbol},
			sq.Eq{"exchange": ex},
			sq.Eq{"is_margin": isMargin},
			sq.Eq{"is_futures": isFutures},
		}).
```

**Comment by lramosduarte** [comment]
Hello @c9s , i think it´s possible to you write 2 ´where´ in sequence, looking at the code will perform just an append.
Like: 
```golang
...Where(sq.Gt{"b": 1}).Where(sq.Lt{"a": 10})
```
But i don't know how the builder(https://github.com/lann/builder) lib works

**Comment by lramosduarte** [comment]
I Think this issue can be closed
