### ISSUE TITLE
hasAny or custom WHERE clause

### ISSUE THREAD

**Issue by sir-farfan** [Masterminds/squirrel#323]
Hello there

I'm trying to set a condition that selects not empty intersection of 2 arrays, an array type column and a user provided list. 

The DB supports a [hasAny](https://clickhouse.com/docs/en/sql-reference/functions/array-functions/#hasany) function for that.

Since squirrel doesn't seem to support it, is there a way of inserting a custom condition with an old fashioned fmt.Sprintf()?

**Comment by sir-farfan** [comment]
I created a custom type in my own code and it seemed to work o:
Please let me know if there's a better way of doing it :)

```golang
type HasAny map[string][]interface{}

func (has HasAny) ToSql() (sql string, args []interface{}, err error) {
	for col, set := range has {
		sql += fmt.Sprintf("hasAny(%s, [%s])", col, sq.Placeholders(len(set)))
		args = append(args, set...)
	}
	return
}
```

**Comment by lann** [comment]
The [`Expr`](https://pkg.go.dev/github.com/Masterminds/squirrel#Expr) function is the general-purpose tool for this sort of thing, but it isn't clear whether it would fit your needs here. Your code looks basically fine to me (assuming the return types are fixed :).

**Comment by sir-farfan** [comment]
I'll check that function in case I need to do something weird in the future.
So far that little interface trick has done the job :)
Thanks
