### ISSUE TITLE
Please update license so GitHub will recognize its type in the API

### ISSUE THREAD

**Issue by mikeschinkel** [Masterminds/squirrel#338]
I am working on a license checker using [the GitHub API](https://docs.github.com/en/rest/licenses#get-the-license-for-a-repository) and it comes back with `NOASSERTION` for this repo rather than `MIT`.  

Would it be possible for you to assert your license type in the Github Admin U so the API response would say `MIT`?

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you in advance or considering.

**Comment by mikeschinkel** [comment]
I know you have the file, but maybe it doesn't recognize it because of the `.txt` extension _(vs. `.md`, or none?)_

**Comment by lann** [comment]
Github appears to know where the license is:

![2022-10-14T09:05:47,418561351-04:00](https://user-images.githubusercontent.com/245734/195854760-720cab28-64ce-4bd5-87c0-ae7aa52c5204.png)

**Comment by mikeschinkel** [comment]
Hi @lann — 

Thank you for such a super-quick response.

Correct. GitHub knows **_where_** your license is, but it does not recognize **_what_** your license is.

However, since I posted this issue I realized that you cannot change it via the admin UI for an existing project but instead you need to edit it so that GitHub will recognize it correctly.  A PR will soon follow for this.

----

BTW, for clarity take a look at what Postman shows when calling [the GitHub API to request your repository's license](https://docs.github.com/en/rest/licenses#get-the-license-for-a-repository):

![Postman](https://user-images.githubusercontent.com/153285/195945667-54c7a193-ff05-4182-af44-4b4920907b6e.png)

And here is what it looks when requesting a license that GitHub recognizes:
![Google's Go License](https://user-images.githubusercontent.com/153285/195946703-bb8edf96-8a8f-48a7-80b6-6652ab8c484c.png)

Next here it what it looks like on the GitHub UI when GitHub knows **_what_** a license is:
![GoLang license](https://user-images.githubusercontent.com/153285/195945831-ea82b444-4dc3-4c5b-b9e6-30b54d4736b1.png)

And here it what it looks like for your repo where GitHub **_does not_** know what your license is:
![Mastermind's Squirrel License](https://user-images.githubusercontent.com/153285/195945958-d491a597-941c-4b69-91a9-ce24172bad0e.png)

**Comment by mikeschinkel** [comment]
As promised, please see #339 that would allow GitHub to recognize your license.

**Comment by mikeschinkel** [comment]
Actually, that did not fix it. Hold on the PR, please...

**Comment by mikeschinkel** [comment]
Okay, so here is the fix:

![Squirrel Fork with Fixed License](https://user-images.githubusercontent.com/153285/195949174-6f7d7b4d-bfb7-45a9-a570-d90be0cd4337.png)

**Comment by lann** [comment]
#339
