### ISSUE TITLE
How to  reuse same wherePart?

### ISSUE THREAD

**Issue by gerardhb** [Masterminds/squirrel#344]
I want to find page list and count with where condtion.  but  I don't know how to build a wherePart and reuse it in select(columns...) and select(count(*)).  I want to build where condition by reflect. but reflection performance is poor. I don't want it to reflect twice.

**Comment by lann** [comment]
Reflection is not slow compared to database access. That said, you should be able to use [`Expr`](https://pkg.go.dev/github.com/Masterminds/squirrel#Expr) for this.

**Comment by gerardhb** [comment]
> Reflection is not slow compared to database access. That said, you should be able to use [`Expr`](https://pkg.go.dev/github.com/Masterminds/squirrel#Expr) for this.

thank you reply. Your reply is very useful to me. I solved my question
