### ISSUE TITLE
Support for TSQL

### ISSUE THREAD

**Issue by lukewilliamboswell** [Masterminds/squirrel#44]
I am interested to know if you think it would possible to support queries which are Microsoft SQL Server friendly? 

I am currently using Microsoft SQL Server on projects with the github.com/denisenkom/go-mssqldb driver and would like to have a tool like squirrel to use for SQL code generation.

I can help with implementation and testing.

Kind Regards

**Comment by lann** [comment]
Some TSQL extensions would fit into the .Prefix or .Suffix methods, but I don't plan on adding much else for dialect-specific methods. That said, much of squirrel is just doing naive string concatenation, so you can often hack sql extensions into place.

**Comment by technosophos** [comment]
@lukewilliamboswell have you had any luck using Squirrel for SQL Server?

**Comment by HeyImAlex** [comment]
@lukewilliamboswell For simple queries the only annoyance has been `TOP`, TSQL's equivalent to `LIMIT`, which I don't think can be done with `.Prefix` or `.Suffix` as it's supposed to come right after `SELECT`.

That being said, SQL Server 2012 added `OFFSET`/`FETCH` which achieves the same thing for the most part, and can be trivially added with `.Suffix`. Only annoying thing is that you have to remember to specify an `ORDER BY` clause.
