### ISSUE TITLE
May I maintain for you?

### ISSUE THREAD

**Issue by technosophos** [Masterminds/squirrel#50]
Would you be interested in letting me maintain for a while?

My proposal would be to move the project under the Masterminds org (pending @mattfarina's agreement), then add you and I as maintainers. If at any point you want to take it back over, you could just do it. And I'd be able to ask you questions for guidance on where this library should go.

**Comment by mattfarina** [comment]
I concur with @technosophos. Only looking to be helpful.

**Comment by lann** [comment]
Sounds good. So I'll transfer to Masterminds?

**Comment by lann** [comment]
Does the original repo just get marked as a fork after a transfer?

**Comment by mattfarina** [comment]
Github puts a redirect in place but the original still works.

For example, we have the repo github.com/Masterminds/glide. This was originally started as a user repo. Do a `go get github.com/technosophos/glide`. That's where it originally started and it works. If you visit the url in the browser it redirects to the new location. If you go get the old location it's in the old place in your `GOPATH`.

Please test it for your own peace of mind. I know I just did.

**Comment by lann** [comment]
Transfer complete. :+1:
