### ISSUE TITLE
Default Timestamp

### ISSUE THREAD

**Issue by BKadishAdFin** [Masterminds/squirrel#54]
There should be a constant or a function called Format Time which can convert from time.Time to a String that can be submitted to psql:

`t.Format("2006-01-02 15:04:05-07")`

**Comment by technosophos** [comment]
We've generally tried to avoid DB-specific code where possible -- a really tough goal, given how each engine does things its own way. Any good ideas on how we might do this in a generic way that could support MySQL, Sqlite, etc.?

**Comment by BKadishAdFin** [comment]
The problem with having a build in function is that the code never really knows what sort of database it is since ToSql() doesn't know the runner so even with say a Timestamp part you would not know how to format the string properly. 

That means the only real way is to have different constants for each database type, which gets you into a mess since mysql and sqlite each have five different date formats so something like this

PostgrestimestampFormat := "2006-01-02 15:04:05-07"
MySQLTIMESTAMPFormat := "2006-01-02 15:04:05"

might still be incomplete.

This ruins a bit of the elegance of your code and is a little far afield from the rest of your library, but it could make it easier to run SQL queries

**Comment by tp** [comment]
Presumably this has been fixed on some level in the meantime.

```go
sq.Gt{"active_to": time.Now()},
```

just works for me in conjunction with `go-sql-driver/mysql`.
