### ISSUE TITLE
Support QueryRow / Query from Update statement for RETURNING clause

### ISSUE THREAD

**Issue by itsjamie** [Masterminds/squirrel#57]
Currently the UpdateBuilder doesn't have support for the Query/QueryRow API, so with PSQL you cannot run a update with a returning clause to get the current values to return a full object representation after a partial update. You have to use the `ToSql()` method call. Any plans on adding this, or should we just continue to use the ToSql after building the query?

**Comment by mattfarina** [comment]
@technosophos @lann thoughts?

**Comment by lann** [comment]
I have generally avoided dialect-specific features, but this one seems pretty harmless and in-line with the go sql API.
