### ISSUE TITLE
Merge v1 into master

### ISSUE THREAD

**Issue by regeda** [Masterminds/squirrel#59]
Hi, All!

As you know `go get` doesn't work with tags or branches in a git repository. So, could you merge v1 into master branch?

**Comment by lann** [comment]
Merging would be fine, but `go get` should be pulling from the remote repo's default branch, which is v1 here.

**Comment by regeda** [comment]
No, `go get` pulling the master. I have tried that.

**Comment by lann** [comment]
Hey, you're right. I thought I had tested this, but apparently not.

**Comment by technosophos** [comment]
@lann I thought you were suggesting people pull from gopkg.in.

**Comment by lann** [comment]
Sure, but I thought the direct import would continue working. The README doesn't mention it anyway.

**Comment by regeda** [comment]
So, guys! What's a conclusion?

**Comment by lann** [comment]
I've updated the README to point at the appropriate gopkg.in URL to get the v1 package. I'm going to hold off on merging to master for now.
