### ISSUE TITLE
`LIMIT ALL`

### ISSUE THREAD

**Issue by xentek** [Masterminds/squirrel#60]
`LIMIT ALL` is valid SQL (and is equivalent to omitting the `LIMIT` clause). `Limit()` only accepts `uint64` values, meaning you can't build a query with this syntax. I have a use case where I have a `SelectBuilder` that has already had `Limit()` called, and I would like to override the clause with `ALL` (or remove it, since it would be equivalent), but neither seem possible at the moment with `squirrel`.

**Comment by lann** [comment]
I can't contribute the patch right now, but I would merge a PR adding a LimitAll method; should be pretty easy to add by copying the Limit method.

**Comment by lann** [comment]
Thanks!
