### ISSUE TITLE
Empty slice shouldn't generate empty IN() SQL statement

### ISSUE THREAD

**Issue by VojtechVitek** [Masterminds/squirrel#61]
Given
```go
squirrel.Or{
  squirrel.Eq{"id": IDs},
  squirrel.Eq{"visible": true},
}
```

Non-empty slice works fine
```go
IDs := []int64{1,2,3}
// generates WHERE id IN (1, 2, 3) OR visible=true
```

But empty slice shouldn't generate `IN ( )` at all
```go
IDs := []int64{}
// should generate WHERE visible=true
```

**Comment by lann** [comment]
I'm not sure that removing the expression is the right thing to do here. In python for example, `id in ()` is always false. I suppose this could expand to `id IN (NULL)`, which I believe would always be false.

**Comment by VojtechVitek** [comment]
@lann you're right. `id IN (NULL)` would be better and works.

**Comment by lann** [comment]
I'll have a patch soonish.

**Comment by lann** [comment]
@nickvanw I noticed that you added an error related to this issue. Any concerns with the above change?

**Comment by lann** [comment]
#62
