### ISSUE TITLE
Anything with ToSql() should also be a fmt.Stringer

### ISSUE THREAD

**Issue by technosophos** [Masterminds/squirrel#64]
I was looking at the API and thinking that we should support `fmt.Stringer` on anything that already has a `ToSql` method. I can't remember if we discussed this back when @lann first wrote Squirrel. It's pretty trivial, so if there's no objection I might knock this out really quickly.

**Comment by technosophos** [comment]
To clarify, what I'm thinking is something like:

```go
func (s *SqlThinger) String() string {
    str, _, _ := s.ToSql()
    return str
}
```

**Comment by lann** [comment]
Sure.

**Comment by tartale** [comment]
Might be nice to include arguments somehow, if possible
