### ISSUE TITLE
Reduce cyclomatic complexity of Update functions

### ISSUE THREAD

**Issue by itsjamie** [Masterminds/squirrel#66]
Currently, for handling PATCH requests from a REST API, we have functions that look like..

```go
query := psql.Update("users").Suffix(returningQuery)

if user.Email != nil { query = query.Set("email", user.Email) }
if user.Name != nil { query = query.Set("name", user.Name) }
...
```

I feel like there should be an easier way to accomplish the goal of partial updates using SetMap, however I haven't found the method by which to skip setting a field if it is Nil.

Does it exist?

**Comment by lann** [comment]
It does not exist since nil is used to represent NULL. If you are setting a lot of fields it might be worthwhile to do something like this (untested):

```go
func StripNilValues(in map[string]interface{}) map[string]interface{} {
    out := make(map[string]interface{})
    for k, v := range in {
        if v != nil {
            out[k] = v
        }
    }
    return out
}

query = query.SetMap(StripNilValues(map[string]interface{} {
    "email": user.Email,
    "name": user.Name,
}))
```

**Comment by itsjamie** [comment]
That makes plenty of sense.

Thanks :)
