### ISSUE TITLE
Support duplicate VALUES in ordinal sq.Dollar format

### ISSUE THREAD

**Issue by itsjamie** [Masterminds/squirrel#68]
So, when you're building a query that uses the same prepared value in multiple locations, currently they are each sent as additional parameters.

It would be nice to be able to take advantage of this.

It isn't supported across multiple drivers like MySQL that use the ? style. Does this make it a no go? Let me know.

Thanks :)

**Comment by lann** [comment]
Yeah, that would be a pretty invasive change and I'm wary of doing much for flavor-specific features.

**Comment by itsjamie** [comment]
Alright.
