### ISSUE TITLE
ToSql() alternative?

### ISSUE THREAD

**Issue by benjamin-thomas** [Masterminds/squirrel#75]
Hi,

I've been playing with your library (feels great!) to handle complex queries based on user input.

I've had the idea of implementing my own intermediary "builder" methods that would help finalize the SQL query and thought about using "test examples" to quickly test the feature.

```go
// builders_test.go, run with `go test -v`

package main

import (
	"fmt"

	sq "gopkg.in/Masterminds/squirrel.v1"
)

func mustPrintSQL(builder sq.SelectBuilder) {
	sql, params, err := builder.ToSql()
	if err != nil {
		panic(err)
	}
	fmt.Print(sql + " ")
	fmt.Println(params)
}

func ExampleBuildSearchWithNoInput() {
	builder := sq.Select("*").From("posts")
	builder = buildSearch(builder, "", "")
	mustPrintSQL(builder)
	// Output: SELECT * FROM posts []
}

func ExampleBuildSearchWithWildcard() {
	builder := sq.Select("*").From("posts")
	builder = buildSearch(builder, "title", "*hello*")
	mustPrintSQL(builder)
	// Output: SELECT * FROM posts WHERE title ILIKE ? [%hello%]
}

func ExampleBuildSearchWithoutWildcard() {
	builder := sq.Select("*").From("posts")
	builder = buildSearch(builder, "title", "Hello!")
	mustPrintSQL(builder)
	// Output: SELECT * FROM posts WHERE title = ? [Hello!]
}
```

I understand the query parameters need to get passed separately to the db driver, but I was wondering if it was possible to inspect the final output, for debugging or testing, especially for very complex queries.

So instead of:

```SQL
SELECT * FROM posts WHERE id = ? [1]
```

I would see

```SQL
SELECT * FROM posts WHERE id = 1
```

Maybe a `ToSQLUnsafe()`, `DumpSQL()` or `DebugSQL()` function?

Any thoughts?

**Comment by lann** [comment]
How about `DebugSqlizer(Sqlizer) (string, error)` with a strongly worded warning in the doc comment about it returning insecure and potentially-invalid SQL?

**Comment by benjamin-thomas** [comment]
Yeah the word "debug" definitely implies that it shouldn't be used in production.

Since this is a narrow use case, do you think returning errors would be useful here?

Maybe just panicking would be fine?

**Comment by lann** [comment]
Panicing seems aggressive for a debug function. It could just return a string and format errors something like "[ToSql error: %s]".

**Comment by benjamin-thomas** [comment]
Sounds great! 👍

**Comment by lann** [comment]
Were you thinking of submitting a PR? I can take a look at it if not, just want to make sure we aren't both working on it.

**Comment by benjamin-thomas** [comment]
I'd really appreciate it if you could look into it, if it's not too much trouble.

Otherwise I could look into it next week, but I'll have to dig into the code first.

**Comment by lann** [comment]
I haven't written a log of Go recently - could you take a look at the patch?

**Comment by benjamin-thomas** [comment]
Looks good to me.

Although some DB engines, like postgersql, require you to quote with single quotes only.

So [this line](https://github.com/Masterminds/squirrel/commit/37cf99044ae366209e4818527135b99b0fb24ef1#diff-22a110c81b7f3ac28a76ae89211e8f86R154)

Would need to probably look like this in some cases.

```go
fmt.Fprintf(buf, "'%v'", args[i])
```

What do you think?

**Comment by lann** [comment]
Sure, that looks like it would probably be correct more of the time.

**Comment by nemosupremo** [comment]
I'm using this with BigQuery which doesn't support prepared statements so this is actually a useful function - `ToSQLUnsafe` probably would have been nicer. I'm working through if there any gotchas with actually trying to use this with an actual database.
