### ISSUE TITLE
Missing OrWhere operator?

### ISSUE THREAD

**Issue by benjamin-thomas** [Masterminds/squirrel#77]
Due to [this line](https://github.com/Masterminds/squirrel/blob/a2b77b08b265b321548a8cb420b389cb6aea44ce/select.go#L99), it seems one can't generate the following SQL.

```SQL
SELECT id, id2, status FROM posts WHERE (id > 1 AND status = 0) OR (id < 100 AND status = 1) 
```

Am I missing something?

I'd like to commit a bunch of example tests, because I feel this could make the documentation better?

Any thoughts?

**Comment by lann** [comment]
ORs are tricky to handle with this library's fluent pattern because it is difficult to make it obvious where parentheses will go. For example, what would you expect the output to be from these two snippets?

```
.Where("x = 1").OrWhere("y = 2").Where("z = 3")

.Where("x = 1").Where("y = 2").OrWhere("z = 3")
```

**Comment by benjamin-thomas** [comment]
Yeah I got confused, sorry!

I got the desired result, with the following:

```go
func ExampleComplexWhere() {
	builder := sq.Select("id, id2, status").From("posts").Where(
		sq.Or{
			sq.And{
				sq.Gt{"id": 1},
				sq.Eq{"status": 0},
			},
			sq.And{
				sq.Lt{"id": 100},
				sq.Eq{"status": 1},
			},
		},
	)
	fmt.Println(sq.DebugSqlizer(builder))
	// Output: SELECT id, id2, status FROM posts WHERE ((id > '1' AND status = '0') OR (id < '100' AND status = '1'))
}
```

What do you think about submitting a bunch of example tests, such as this one?

**Comment by lann** [comment]
Please do!
