### ISSUE TITLE
Arguments in OrderBy scope

### ISSUE THREAD

**Issue by ei-grad** [Masterminds/squirrel#78]
It is not possible currently to construct a query with arguments in OrderBy clause via squirrel, for ex.:

```go
Select("*").From("geo").OrderBy("ST_Distance(ST_Point(lng, lat), ST_Point(?, ?))", lng, lat)
```

**Comment by elewis787** [comment]
I would move the ST_Distance(ST_Point(lng, lat), ST_Point(?, ?) to the select and alias the result. 

```Select("*", "ST_Distance(ST_Point(lng, lat), ST_Point(?, ?) as stdist",lng,lat).From("geo").OrderBy("stdist")```

**Comment by mennanov** [comment]
Any plans to add support for this?
There are situations when you can't extend the Select/Update clause:

```go
query := sq.Update("*").From("table")

switch order {
  case option1:
    // No .Update() method here. Does not work.
    query = query.Update("*", "orderFunction(..) as ord") 
    query = query.OrderBy("ord")
  case option2:
    query = query.OrderBy("...")
}
```
