### ISSUE TITLE
Support FROM clause in UpdateBuilder

### ISSUE THREAD

**Issue by scags9876** [Masterminds/squirrel#82]
Trying to construct an update statement like the following in squirrel is proving impossible:

```sql
-- Update value in table a for all rows where the associated table b row has specified value in test_column
UPDATE table_a
SET table_a.value_column = $1
FROM table_b
WHERE table_b.a_id = table_a.id 
and table_b.test_column =  $2
```

I think UpdateBuilder should support a FROM clause to be able to leverage the abilities of postgres updates syntax: https://www.postgresql.org/docs/current/static/sql-update.html

**Comment by sdalezman** [comment]
We have a few scenarios where this would be helpful like when we have a large number of rows that we know the exact values to update. We're right now constructing this query ourselves 

I'm happy to open a pr adding support for this, but just wanted to make sure it's something that will be accepted/there's interest for before doing the work  

also just want to say we love the lib!

**Comment by lann** [comment]
I've generally tried to avoid dialect-specific methods, but since there isn't a good way to work around this one I'd accept a new UpdateBuilder From method here.

**Comment by mlaflamm** [comment]
Why is this issue closed? There is a PR but it is still open.

**Comment by mlaflamm** [comment]
I've created a new PR that corrects the original one from @sivagollapalli.

**Comment by cjea** [comment]
Any update on this?

**Comment by ysomad** [comment]
Any updates on this?

**Comment by denolehov** [comment]
Any update on this? The issue is closed, but the PR is open 😓
