### ISSUE TITLE
Upsert/On Conflict support

### ISSUE THREAD

**Issue by nitronick600** [Masterminds/squirrel#83]
Hello, I looked through this repo for some way to support Postgres's 'on conflict' mechanism. Is there a recommend approach for using that?

Thanks

**Comment by lbeeon** [comment]
Any progress?

**Comment by lann** [comment]
Squirrel does not support dialect-specific SQL extensions, but there are some generic mechanisms to handle them. In this case the following should work (untested):

```go
.Suffix("ON CONFLICT DO UPDATE SET foo.bar = ?", 1)
```
