### ISSUE TITLE
Support for Upsert on PG?

### ISSUE THREAD

**Issue by ehmo** [Masterminds/squirrel#90]
Hi guys,

Great library. Was using it for the past day or so and was wondering if there is a support for the Postgresql's Upsert [ON CONFLICT](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT) statements.

**Comment by RoarkeRandall** [comment]
should be merged w/ https://github.com/Masterminds/squirrel/issues/83

**Comment by lann** [comment]
Dupe of #83
