### ISSUE TITLE
Quoting fields

### ISSUE THREAD

**Issue by shuhaowu** [Masterminds/squirrel#94]
From what I can see, squirrel currently does not quote the SQL queries it generates, which could lead it to generate some invalid queries like:

```
INSERT INTO table (group) VALUES (?)
```

Note that since `group` is not quoted, something liky MySQL will interpret it as the reserved keyword `GROUP`, which causes a syntax error.

Are there any plans to address this in the SQL builder? Would a PR for this make sense? I have yet to look deeply into the codebase, but would this be difficult to change in squirrel?

**Comment by lann** [comment]
Squirrel does not currently attempt to support database-specific syntax. There is a standard of using double quotes for identifiers but not all database engines allow it by default (e.g. MySQL requires "ANSI mode" to be turned on).

I may add such support in the future but it would probably be a v2 API breaking backward compat with the current API.

**Comment by shuhaowu** [comment]
For people finding this bug in the future, a workaround could be pre-quoting the fields you give to Squirrel, this would ensure it builds a quoted query.

**Comment by donotnoot** [comment]
I'll just leave this comment for people using search (at least this is what I searched the issue tracker for): backticks

As @shuhaowu said, the best way to deal with this, is to pre-quote (or pre-backtick) your field names, it worked for me too :+1:
