### ISSUE TITLE
Support for INSERT INTO SELECT

### ISSUE THREAD

**Issue by tartale** [Masterminds/squirrel#95]
[Reference](https://www.w3schools.com/sql/sql_insert_into_select.asp)

Currently, due to the requirement to have at least one item specified in `Values()`, the Insert Builder does not support this possibility (even through use of `Suffix`()):

```sql
INSERT INTO table2
SELECT * FROM table1
WHERE condition;
```

**Comment by MasseElch** [comment]
I can confirm, that this does work now. 
This issue should be closed.

For everyone landing here: 

```
squirrel.
    Insert(kDeletedProductTransfersTable).
    Select(
        squirrel.
        Select("*").
        From(kProductTransfersTable).
        Where("id = ?", pt.ID)
    )
```
