### ISSUE TITLE
byte array in the where clause gets expanded into IN (?, ?, ?, ?, ...)

### ISSUE THREAD

**Issue by shuhaowu** [Masterminds/squirrel#96]
Say that you have a TEXT field (`t`) in your database and you want to filter with `WHERE t = ?` `[someValue]`.

In squirrel, this would be addressed as something like:

```
whereMap := map[string]interface{}{
  "t": "value"
}
sq.Update(tableName).SetMap(setMap).Where(whereMap).ToSql()
```

This works great, with squirrel generating `WHERE t = ?` `[value]` as the sql and args.

However, let's change the code above to have a byte array:
```
whereMap := map[string]interface{}{
  "t": []byte("value")
}
sq.Update(tableName).SetMap(setMap).Where(whereMap).ToSql()
```

This would result in the following query:

```
WHERE t IN (? ? ? ? ?) 
[118 97 108 117 101]
```

I'm not sure if this is the correct behaviour or not in squirrel, but this is definitely not the right query to generate.

I'm proposing that `squirrel.Eq` forces the generation of `t = ?`, even if the value given is an array. Would that work?

**Comment by lann** [comment]
Yeah, clearly a bug. I'll fix it.
