### ISSUE TITLE
Empty slice generates NOT IN(NULL) SQL statement

### ISSUE THREAD

**Issue by Julusian** [Masterminds/squirrel#99]
Follow up to #61 

I have hit an issue with the decided upon solution for #61.

When the query is built as ```WHERE id IN (NULL)``` I get 0 rows as I would expect, but if the query is ```WHERE id NOT IN (NULL)``` I also get 0 rows when I would instead expect it to find every row. 

So in the case where the operation is a NOT IN it would make sense to drop the condition completely.

**Comment by lann** [comment]
Thanks for the report; take a look at #100

**Comment by lann** [comment]
Had to revert the fix due to #101.

**Comment by lann** [comment]
New fix, now with 100% more regression test.

**Comment by Julusian** [comment]
I have just had a chance to test this and it appears to be working now.
Thanks
